### ISSUE TITLE
Send Later mails are PGP encrypted

### ISSUE THREAD

**Issue by msebald** [Extended-Thunder/send-later#38] opened 2020-10-19 19:26 UTC
Hi,

I am using Thunderbird 78.3.2 and Send Later 8.0.3. I also use the new PGP implementation of Thunderbird instead of Enigmail which will not developed any further.

When sending a mail later it is sent out encrypted. This could be ok if I flagged the mail to be encrypted. But I do not. Also mails are sent out encrypted even if I do not have a public key of the recipient.

Not idea if this is a core problem of Thunderbird (I understand that a Send Later mail is saved as draft in the drafts folder) or a problem with the Send later addon. But I have to start somewhere, so I am bringing this up here. ;-)

Kindest regards,
Martin

**Comment by jperryhouts** [comment] 2020-10-19 19:53
This is a duplicate of #26 and is on my shortlist of todo items (likely next weekend). Unfortunately, the solution will likely be to disable send later scheduling if encrypted drafts are enabled. Keep an eye on that issue for updated info on this.

**Closed by jperryhouts** 2020-10-19 19:53 UTC
Labels: duplicate

**Comment by msebald** [comment] 2020-10-19 19:58
Thank you. Sorry, I was not aware of #26, will subscribe to this issue. And also will look there if I can disable encrypted drafts (as sending some mails encrypted is enough for me).

**Comment by jperryhouts** [comment] 2020-10-19 20:03
Comment in #26 if you figure out how to disable encrypted drafts without disabling Enigmail entirely. It may be easy to do, but I don't use Enigmail these days, so I'm not sure how to advise users about this issue. Thanks!

**Comment by msebald** [comment] 2020-10-19 20:06
> Comment in #26 if you figure out how to disable encrypted drafts without disabling Enigmail entirely. It may be easy to do, but I don't use Enigmail these days, so I'm not sure how to advise users about this issue. Thanks!

I am not using Enigmail anymore, too. I use the built-in encryption system which is new to Thunderbird 78+.

Commented on the other issue.

**Comment by jperryhouts** [comment] 2020-10-19 20:13
Sorry, that's what I meant. Let us know in #26 if you figure out how to disable encrypted drafts now that Thunderbird bundles OpenPGP
