### ISSUE TITLE
Scheduled messages sometimes sent twice

### ISSUE THREAD

**Issue by martinmagnusson** [Extended-Thunder/send-later#399] opened 2021-11-12 08:19 UTC
Sometimes emails that are scheduled are sent twice. I get two copies of the email in my Sent folder (1 minute apart), and the recipient gets two copies as well. 

I have not yet been able to find a pattern as to when it happens. Today, I had 7 emails scheduled, of which 3 were duplicated and 4 sent normally.

Thunderbird 78.13.0, send later 8.9.8, Kubuntu 20.04

**Comment by jph-sendlater** [comment] 2021-11-20 17:14
Keep an eye out for any details that might help track this down. Like, patterns with when this happens. Maybe it only happens with certain recipients? Maybe it happens with messages that were edited after being first scheduled? I don't know exactly what to look for, but anything you think might be relevant to figuring out the cause.

Thanks!

**Comment by martinmagnusson** [comment] 2021-12-07 11:53
FWIW, here is one observation. Today a number of messages were sent twice. I had them scheduled for 8:00 when the computer was suspended, but then resumed the laptop at 8:15, and I have copies of the emails in my Sent folder from 8:15. So far, so good, but they also seem to have been added to the local Outbox folder as if I would have been offline. Later, the messages in the Outbox were sent out, so duplicates of the ones I had already sent. Presumably, on the first attempt to send the emails after resuming, there was no network connection, so the messages were put in the Outbox -- but then also actually sent out. Some kind of race condition? For the record, my incoming server is an office365 email server that I connect to with IMAP and SMTP, and authenticate for sending messages with OAuth2.

**Comment by jph-sendlater** [comment] 2021-12-19 21:52
I still don't have a good answer for you, but one thing you might try is disabling the "`sendWhileOffline`" preference, which will prevent Send Later from putting messages in the Outbox until Thunderbird is fully online.

That preference is not exposed in the options menu, so you'll need to expand the "`Advanced configuration editor`", and find the row with `"sendWhileOffline": true,` Change the `true` to `false`, and click `Save` at the bottom of the editor.

I can't guarantee that will have any effect, but it's worth a try.

**Comment by martinmagnusson** [comment] 2021-12-23 07:42
I changed the above, but then my scheduled messages are not sent at all, it seems -- which is very strange. At least not today. They just sit in the draft folder, with a "send later" date in the past. I will try to uncheck the "Trigger unsent message delivery from Outbox" instead and see if that has the intended effect?

**Comment by martinmagnusson** [comment] 2021-12-23 09:12
A restart of Thunderbird might have helped the above. I will try to trouble shoot a little more, and get back.

**Comment by martinmagnusson** [comment] 2022-01-28 07:26
One more observation. Two emails were scheduled to be sent at 8:00. The computer was suspended at that time, and was resumed around 8:15. Both emails were successfully sent then, but a copy of each of them was also placed in "Local Folders / Outbox". Thunderbird asked me if I wanted to send my unsent messages (i.e., from the Outbox). I said no, but left them in the Outbox. A minute later (now at 8:19) sendlater was triggered again, and sent out one of the two emails again. The second one was not sent, but I got the popup warning me that it had already been sent and that my folder might be corrupt. I will try to uncheck the "Trigger unsent message delivery from Outbox" setting and see if that helps.

**Comment by jikamens** [comment] 2022-10-05 15:59
Are you running Thunderbird on multiple computers with the profile copied from one computer to the other or on a network drive?

Is your Outbox folder stored in Local Folders or on the IMAP server?

**Comment by martinmagnusson** [comment] 2022-10-06 03:15
This problem actually hasn't happened to me for a while now, but to answer your questions: it is all on one computer, and the Outbox folder is in Local Folders.

**Comment by jph-sendlater** [comment] 2022-11-13 21:41
A lot has changed in Send Later since this was first reported. I'm going to close this issue for now, but let me know if the problem reappears.

**Closed by jph-sendlater** 2022-11-13 21:41 UTC
