### ISSUE TITLE
Not accepting the time that I set.

### ISSUE THREAD

**Issue by RickiRu** [Extended-Thunder/send-later#370] opened 2021-09-06 14:46 UTC
I set an email to be sent at 8:00am and it gets set to go at 7:40am.

Thunderbird version: 78.13.0
Send- later version: 8.9.6

**Comment by jph-sendlater** [comment] 2021-09-06 15:05
Can you explain what exactly happens? Does the time input box change after you've typed 8:00? Does the "Send at ...." button show 7:40? Or does everything indicate it should send at 8 until you schedule it, and then the date in the send later column is 7:40?

**Comment by RickiRu** [comment] 2021-09-06 15:07
When I set it to 8:00am the "Send at..." shows 8:00am.
It is only when it goes into the Draft folder it then shows 7:40am in the "Send later" column..

**Comment by jph-sendlater** [comment] 2021-09-06 15:21
Is it specific to 8:00 -> 7:40, or does this happen with other times as well? What exactly are you entering in the 'send at' box (i.e. are you entering "8:00" in the text field, or something else?

Try opening the error console (Ctrl+Shift+J), and then schedule a message again. It should show a message something like the following:

![image](https://user-images.githubusercontent.com/75693008/132237794-6338b92e-ca9f-4fdd-b0c5-765f782ce593.png)

Does it say the correct time after "sendAt: "? Are there any other suspicious errors along with that message?

Lastly, once the message is saved, look at its headers (view the message in your drafts folder and click Ctrl+U to view its source), then find the line near the top starting with "X-Send-Later-At". What does that line say?

**Comment by RickiRu** [comment] 2021-09-06 15:40
Ctrl_Shift_J

1630939891565	addons.xpi	WARN	Exception running bootstrap method startup on twitter@search.mozilla.org: Error: Error while loading 'jar:file:///C:/Program%20Files%20(x86)/Mozilla%20Thunderbird/omni.ja!/chrome/messenger/search-extensions/twitter/manifest.json' (NS_ERROR_FILE_NOT_FOUND)(resource://gre/modules/Extension.jsm:570:20) JS Stack trace: readJSON/</<@Extension.jsm:570:20
onStopRequest@NetUtil.jsm:128:18

Send Later version 8.9.6 on Thunderbird 78.13.0 (20210802223056) [win x86-32] background.js:27:15
1630939891726	addons.webextension.<unknown>	WARN	Loading extension 'null': Reading manifest: Warning processing legacy: An unexpected property was found in the WebExtension manifest.
WebExtensions: INFO [SL3U]: onLoadWindow, inject script jar:file:///C:/Users/admin/AppData/Roaming/Thunderbird/Profiles/5j23d9td.default/extensions/sendlater3@kamens.us.xpi!/utils/sugar-custom.js sl3u.js:122
WebExtensions: INFO [SL3U]: onLoadWindow, inject script jar:file:///C:/Users/admin/AppData/Roaming/Thunderbird/Profiles/5j23d9td.default/extensions/sendlater3@kamens.us.xpi!/utils/static.js sl3u.js:122
Ruleset ignored due to bad selector. style.css:5:1
.....................................................................................................................
Ctrl_U

Message-ID: <4ef038dc-9de2-e1ed-cba9-23aec6c9669c@sa.aeva.asn.au>
X-Send-Later-Uuid: {fb2f23ac-260e-45b1-b748-1d2a94b9c05d}
X-Send-Later-At: Tue, 7 Sep 2021 08:00:00 +0950
X-Send-Later-Recur: none
Date: Mon, 6 Sep 2021 23:58:10 +0930
................................................................................................

In the message "Send Later  9/7/2021 7:40AM"

​

**Comment by RickiRu** [comment] 2021-09-06 15:41
It is late - going to bed - more tomorrow.
Australia...

**Comment by RickiRu** [comment] 2021-09-06 15:43
Before I go - I tried another test message and that set itself to be sent exactly 20minutes before as well.

**Comment by jph-sendlater** [comment] 2021-09-06 15:45
Are they actually sending 20 minutes early, or is it just displaying that way in the send later column? It looks like the `X-Send-Later-At` header is correct

**Comment by jph-sendlater** [comment] 2021-09-06 15:47
Oh, wait. I might see the problem here. Give me some time to think about it, but it looks like there's something up with your timezone offset, and I think I might know why. I'll fix this later today.

**Comment by RickiRu** [comment] 2021-09-06 15:48
they get sent 20 minutes early as displayed in the Send later column.
... and my computer time is set right.

**Comment by jph-sendlater** [comment] 2021-09-06 16:00
:+1: Got it. The problem isn't with your timezone, it's with the way your timezone shows up in the x-send-later-at header. I changed the way those dates are formatted between v8.9.5 and 8.9.6, and it looks like I got it wrong for time zones which are offset by 30 minute increments rather than full hours. I'll look into it more later today.

**Comment by jph-sendlater** [comment] 2021-09-06 16:48
This is fixed in version 8.9.7, which is just waiting on approval by the Thunderbird reviewers.

**Closed by jph-sendlater** 2021-09-06 16:48 UTC

**Comment by RickiRu** [comment] 2021-09-06 22:39
Thanks
