### ISSUE TITLE
Format for shortDateTimeFormat & longDateTimeFormat

### ISSUE THREAD

**Issue by tomatic** [Extended-Thunder/send-later#488] opened 2022-12-01 06:09 UTC
I'm trying to set a custom date format to circumvent the issue described in #409 and #401. But I can't seem to figure out the correct format for the date/time and it doesn't seem to be documented. I even checked the releases but couldn't find the commit(s) where this feature was added.

I tried `"shortDateTimeFormat": "dd.MM.yyyy, hh:mm"`, but when I reopen a scheduled email, that string just appears in the date field, as in literally:

![ksnip_20221201-070049](https://user-images.githubusercontent.com/367058/204978236-6d1747b2-5619-42cc-966b-5b2fcc306626.png)

I also tried "dd.mm.yyyy", same result:

![ksnip_20221201-070230](https://user-images.githubusercontent.com/367058/204978266-31197a8c-b09b-420f-8184-5692d12bb57f.png)

Is this how it's supposed to work or am I doing something wrong? Because I was expecting the date/time field to be pre-filled with the previously scheduled date/time based on my custom format string.

**Comment by jikamens** [comment] 2023-08-25 02:20
Please see https://extended-thunder.github.io/send-later/#custom-dates which now documents how to set a custom date format. Note, however, that as of [release 10.0.5](https://github.com/Extended-Thunder/send-later/releases/tag/v10.0.5) you shouldn't need to set a custom date format to work around those bugs because they should be fixed for most people. If you'd like you can download the pre-release XPI there and try it out to confirm that the issue is fixed for you.

**Closed by jikamens** 2023-08-25 02:20 UTC

**Comment by tomatic** [comment] 2023-08-25 06:40
Thanks for the follow-up. I'll wait for the release version and report back if the issue persists.
