### ISSUE TITLE
content of the "send later" window disappears after closing and reopening

### ISSUE THREAD

**Issue by julianpoemp** [Extended-Thunder/send-later#362] opened 2021-08-15 08:05 UTC
1. Click on "Send later"
![Bildschirmfoto 2021-08-15 um 09 57 31](https://user-images.githubusercontent.com/25926588/129471410-e76820e1-b490-4227-b408-1894ef077f22.png)

2. Close and open it again
![Bildschirmfoto 2021-08-15 um 10 00 37](https://user-images.githubusercontent.com/25926588/129471452-08abc1a5-ad6d-435b-ab9e-daccbd7aaae5.png)

If I move the mouse over the empty window the cursor Icon doesn't change. That's why I think, that all elements of the window were cleaned or hidden.

It would be nice to have a dark theme window 😄 , too. 

### System information

OS: MacOS 11.4
Thunderbird: 91.0 64bit
Enabled Theme: System Theme by Thunderbird (OS Theme is dark, so Thunderbird is dark, too)
Enabled Addons: Addon Compatibility Check, Automatic Dictionary. Dark Reader, Darko, FiltaQuilla, Send Later

**Comment by jph-sendlater** [comment] 2021-08-15 16:40
Send Later doesn't handle low-level operations like rendering the UI elements (or themes for that matter). This appears to be a duplicate of #328, #333, #361, etc. It's supposedly fixed in the latest beta. See https://bugzilla.mozilla.org/show_bug.cgi?id=1710608 and https://bugzilla.mozilla.org/show_bug.cgi?id=1690987 for more details.

**Closed by jph-sendlater** 2021-08-15 16:40 UTC
