### ISSUE TITLE
ISSUES with getting stuck in drafts

### ISSUE THREAD

**Issue by sharkmullet** [Extended-Thunder/send-later#501] opened 2022-12-14 18:12 UTC
### Discussed in https://github.com/Extended-Thunder/send-later/discussions/500

<div type='discussions-op-text'>

<sup>Originally posted by **sharkmullet** December 14, 2022</sup>
I don't know why they never leave the drafts folder. I tried repairing the drafts folder, and I also restarted my computer.

Messages don't leave the drafts folder after the time they were supposed to go.

What do i do?</div>

**Comment by igustin** [comment] 2022-12-15 07:37
Same here, in addition to painfully slow Thunderbird, so I have to disable this add-on until next update with fix.

**Comment by TkaczSnow** [comment] 2022-12-15 07:58
Same here - addon not working - scheduled messages are not sent. Additionaly there is no status that addon has planned messages and Thudnerbird has big lag (slowness). Version : 9.2.4.

**Comment by PaoloPC** [comment] 2022-12-15 15:02
Reverting to the 9.1.1 version https://github.com/Extended-Thunder/send-later/releases/tag/9.1.1, fixes the problem (well, at least you can continue to use the add-on until a fix comes out)

**Comment by philpav** [comment] 2022-12-20 09:41
Same problem here with Thunderbird 102.6 and Add-On version 9.2.4 on MacOS 13.0.1.

**Comment by damienjadeduff** [comment] 2022-12-21 07:38
MacOS 12.5.1 intel hardware - Thunderbird 102.6.0 64-bit - SendLater 9.2.4 
Downgrading SendLater fixed.

**Comment by jph-sendlater** [comment] 2022-12-24 01:23
The performance issues should be improved in 9.2.5 (awaiting approval on ATN, or available [on github](https://github.com/Extended-Thunder/send-later/releases/tag/9.2.5)). I'm not sure about the stuck messages, but it's possible that improving performance will solve that as well. Let me know if this is still happening when you've had a chance to try the new version.

**Comment by jph-sendlater** [comment] 2022-12-26 20:38
Anyone who's still on version 9.2.x, could you check the following:

1. Check the Send Later browser action button in the top right of the main Thunderbird window (near the hamburger menu).
    - It should have a badge with a tiny number that corresponds to the number of scheduled messages you have- Is that number accurate?
    - When you click the button, you should get a popup that lists all your scheduled messages. Do all your scheduled messages show up in that list?
2. If that badge counter and/or the popup list is incorrect, try restarting Thunderbird. If it finds the messages during start-up, but doesn't recognize newly scheduled ones that would be a clue I could work with.

**Comment by PaoloPC** [comment] 2022-12-27 17:44
Hello Jonathan, 
I have installed version 9.2.5 from GitHub to do some testing. 
The action button does not have a badge or numbers (see https://imgur.com/iEUVyAj.png). 
Additionally, the popup is blank (see https://i.imgur.com/pX0utod.png). 
I restarted Thunderbird (version 102.6.1), but there were no changes. I am testing on MacOS Ventura, but I am seeing the same behavior on my Linux workstation.

**Comment by jph-sendlater** [comment] 2022-12-28 23:41
Please try the newest version (version 9.2.7 which is available through the normal thunderbird add-on auto-updater or 9.2.8 which is the latest one on Github.

**Comment by TkaczSnow** [comment] 2022-12-29 06:49
I have instaled verssion 9.2.7 trough auto-updater over 9.1.1, restarted Thuderbird and planed outgoing email (2 min).
Saddly, I dont have badge counter anywhere in UI and scheduled messages not leave sketches section - tried 3 times.
My system: Windows 10 PRO 22H2 64bit, Thunderbird 102.6.1 32 bit.

P.S. Thank You for this wonderfull addon and support!

**Comment by PaoloPC** [comment] 2023-01-04 14:19
> I am using Windows 10 Pro 21H2 64 bits and Thunderbird 102.6.1 (32 bits).

Try running Thunderbird from the command prompt (something like "c:\Program Files\Thunderbird\thunderbird.exe") to spot any error logs. 
During my tests, after launching the program from the command prompt once, the extension began to work correctly as expected.

**Comment by oliviergenest** [comment] 2023-01-05 13:11
Thanks for your suggestion.
I tried to launch Thunderbird from the command prompt but I do not see any error and the issue remains the same.

**Comment by PaoloPC** [comment] 2023-05-05 12:45
I was stuck on the 9.1.1 version, but now I'm happily using the 9.2.9 version.
To get the last version to work, I started Thunderbird with a new profile, reconfigured all my email accounts, and the Send Later plugin is working correctly as expected, including drafts on the remote IMAP server. 

I suppose my old Thunderbird profile, which was many years old, was somehow corrupted or not working well with Send Later.

**Comment by jikamens** [comment] 2023-07-26 21:30
If anyone who has commented on this ticket is still having problems with Send Later 9.2.9, please comment and describe exactly what you're seeing so I can troubleshoot further.

Notes:

* Send Later is not yet supported for TB115.
* If you have more than 100 messages in your Drafts folder, then the root cause of your issue may be as described in #529, a fix for which will be included in the next Send Later release.
* If you do not see the "Send Later" column in the list of columns available for display in your Drafts folder, then you may be running into a known race condition in the Send Later start-up code which we're hoping will be fixed in the next Send Later release.

If none of these three caveats applies to you, then please describe what you're seeing so we can try to troubleshoot further.

**Comment by oliviergenest** [comment] 2023-07-27 17:10
Hello,
I still have the same issue with version 9.2.9.
Here is a capture of the SendLater panel : 
![image](https://github.com/Extended-Thunder/send-later/assets/47632278/737bcf39-eb30-46dc-9dbc-9b874ae5acef)

Also I cannot see the "Send later" column in the Draft folder, and I have 397 e-mails in this folder.

Hope this helps!
I will move back to 9.1.1, waiting for the new version 🙂 Thanks for your support

**Comment by jikamens** [comment] 2023-08-08 20:15
For those of you here who are reporting that the current version of Send Later is very slow, do you have Thunderbird configure to save copies of messages locally? If you either enable the "Keep messages in all folders for this account on this computer" checkbox on the "Synchronization & Storage" tab of your account settings, _or_ you open the properties for your Drafts folder and check "Select this folder for offline use" on the "Synchronization" tab, that should speed things up considerably.

Unfortunately there's currently no way for Send Later to fetch just the headers that it needs when scanning messages in your drafts folder; it has to fetch every message in its entirety. But this should be much faster if you enable synchronization as described above.

The other issues with messages getting stuck intermittently should be fixed in the [beta release for TB115](https://github.com/Extended-Thunder/send-later/releases/tag/v10.0.0) and those fixes will eventually be backported to TB102.

**Comment by jikamens** [comment] 2023-08-09 13:45
I'm closing this issue because I believe the drafts getting stuck problem is fixed in Send Later 9.3.0 for TB109 or 10.0.1 for TB115.
Feel free to reopen or comment on the issue if you're still seeing it.
As noted above, I believe configuring your Drafts folder for local synchronization will resolve the performance issue.

**Comment by kkmdmdkk** [comment] 2023-08-22 11:26
Hello, I am telling you my contribution that may solve the problem for some.

Just today I discovered that Thunderbird was showing me the message: "The folder drafts is full, and can't hold any more messages. To make room for more messages, delete any old or unwanted mail and compact the folder."

After inquiring on the Internet in various forums about Thunderbird, this is because the default program assigns in each folder (inbox, draft folder, sent folder) a default capacity of 4Gb on the computer.

To solve this small problem, if you use Thunderbird, I leave you this link (in spanish, to translate it you will have to use Google Translate) where it explains very simply and clearly how to expand the capacity to everything you have on your hard drive, without having to compact or delete nothing: [https://www.consejosytrucos.net/noticias-740609/como-aumentar-tu-limite-del-buzon-de-correo-en-thunderbird/](https://www.consejosytrucos.net/noticias-740609/como-aumentar-tu-limite-del-buzon-de-correo-en-thunderbird/)

Perhaps the Send-Later limit has to do with Thunderbird's default 4Gb deleted folder limit.

However, I currently have 37 emails pending sending by Send-Later in my draft folder. The day I exceed the famous 100 emails I will post what happens on my computer. Because this is a very interesting topic.

**Comment by 121sim** [comment] 2023-08-28 10:12
> https://github.com/Extended-Thunder/send-later/releases/tag/v10.0.3
> 
> Can those of you who are still having this problem give it a try?

Hi,

the issue seems to persist on my side ; i've tried with the 10.0.9 release, on 102.14.0 Thunberdird.
I'm running MacOs.

I tried with all other addons disabled. I'm gonna try with a new & empty profile.

I can paste any relevant code or file if needed.

Thanks.

**Comment by jikamens** [comment] 2023-08-28 22:26
@121sim please comment here if the problem persists in a new profile and we'll troubleshoot further.

I'm sure this is frustrating to people, for which I am sorry. It's also frustrating to me, because I've fixed several things that were causing messages to get stuck in Drafts for _some_ people, but there just always seem to be more of them. Maybe if we keep at it for long enough we'll get them all fixed? :shrug:

**Comment by oliviergenest** [comment] 2023-08-28 22:40
Dear all,
It seems to work fine now with TB 115.1.1 and SendLater 10.0.4.
Thanks for improving this plugin!

**Comment by 121sim** [comment] 2023-08-29 08:32
Actually, according to the previous comment, is this relevant to keep trying with the 102.14.0 or should i move directly to 115 ?

I'm not able to try with a new profile, as when i create one, Thunderbird loops on some weird issue (Rethrowing (from nts_ValueForProperty:) NSInternalInconsistencyException: Unhandled error (NSCocoaErrorDomain).

Tho, with a new MacOs session and (therefore) a new profile, SendLater does work perfectly.

It made me spot something i was not sure about : in the send later window, on the profile that doesn't work, timings differs. I'm attaching pictures.

![1](https://github.com/Extended-Thunder/send-later/assets/74899182/152b21d8-8340-42b6-8355-a43eeb77a11f)

![2](https://github.com/Extended-Thunder/send-later/assets/74899182/abf83d8c-726f-4f8a-adc8-bde051279e77)

![3](https://github.com/Extended-Thunder/send-later/assets/74899182/0c52769e-811d-4b7e-8a56-a3b4c7f163ff)

I don't know if it's relevant.

Thanks.

**Comment by jikamens** [comment] 2023-08-29 13:21
>Actually, according to the previous comment, is this relevant to keep trying with the 102.14.0 or should i move directly to 115 ?

I don't think that there are differences between 102 and 115 in this particular area at this point, though I certainly can't say for certain since there may be things I'm unaware of under the hood in Thunderbird that are different between the two platforms and relevant.

Having said that, if there aren't any other add-ons you need that are currently supported in 102 but not 115 then I'd suggest switching to 115 if I were you.

>I'm not able to try with a new profile, as when i create one, Thunderbird loops on some weird issue (Rethrowing (from nts_ValueForProperty:) NSInternalInconsistencyException: Unhandled error (NSCocoaErrorDomain).

This would seem to point to there being an issue with your Thunderbird install and you might need to wipe it and start from scratch to fix this. Hopefully you're not storing any email locally in your profile as opposed to exclusively in folders on an IMAP server, because if you have local messages, then wiping and recreating your profile becomes more complicated. Not impossible, just more complicated.

Having said that, I want to be clear that I can't 100% guarantee that wiping your Thunderbird config and starting from scratch will fix this. The fact that you said this...

>Tho, with a new MacOs session and (therefore) a new profile, SendLater does work perfectly.

...seems to imply that it will, but I can't be 100% certain. At least it does seem to make it clear that the problem isn't with Send Later.

If you want to try erasing and recreating your Thunderbird config completely, I believe you would need to delete Library/Thunderbird. Make sure Thunderbird isn't running when you do this. ;-)

>It made me spot something i was not sure about : in the send later window, on the profile that doesn't work, timings differs. I'm attaching pictures.

The add-on tries to estimate the actual delivery time of a message based on the current time and how frequently you have it configured to check for scheduled messages due to be delivered. I.e., it looks at when that check last took place and will next take place when displaying the estimated time in the button. That's why you see the difference here, nothing more.

This change was made by the previous maintainer of the add-on, and I'm not sure I agree with it—I think it may introduce more confusion than clarity—so I might undo it at some point, but for the time being, that's why it's behaving that way, and it isn't relevant to the problem we're discussing.

**Comment by 121sim** [comment] 2023-08-29 14:18
Thanks for all the details.

As you said 115 version doesn't change anything related to this issue. This is for sure an old profile, it must have accumulated a lot of layers since all that years, and i'm ok that a startover is adviced.

(as for the loop on creating a new profile it's sorted out : deleting all the Contacts in Apple's contact app did the job.)

**Comment by mcsalop** [comment] 2023-08-30 20:30
Problem has just started for me - TB 102.14.0 (64-bit) on W10, Send Later updated yesterday to 10.1.0 and the problem started (it also refused to send emails because drafts were encrypted, apparently - strange, since I've never used encryption, and the option to not encrypt them was greyed out - had to change it in the config editor)

I only have a handful of emails in the draft folder. The Send Later column is visible, but if I resize it and close Thunderbird, when I reopen the column returns to the original width.

The badge shows the correct number of waiting emails initially - but if I open them and send them manually, the number doesn't update.

**Comment by jikamens** [comment] 2023-08-30 20:41
@mcsalop This issue should be fixed in release 10.1.3 of Send Later.

This release is available on addons.thunderbird.net, and unless you've turned off automatic add-on updates, Thunderbird will eventually update to the new version automatically. To update immediately:

* Go to [addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/versions/) and confirm that release 10.1.3 is available for download there.
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click on Send later.
* Click the gear icon and select "Check for Updates".
* The add-on should update and then you should see the message, "Your add-ons have been updated," next to the gear icon.

Please let me know if you still see this issue in this release.

**Comment by mcsalop** [comment] 2023-08-30 21:07
Excellent - works perfectly, thank you!

**Comment by jikamens** [comment] 2023-09-01 01:08
Hello kind people! If you are still, with release 10.1.3, having problems with drafts not being delivered, then I have another fix for you to try.

A Send Later user who was having this problem generously gave me more than an hour of his time on Zoom today so I could troubleshoot on his computer directly, a necessity for making further progress on this because I wasn't able to identify what the issue was any other way. We discovered that when Thunderbird can't talk to a particular email account, either because the mail server associated with the account is offline or perhaps also because the user's login on that server has been deactivated, attempts by Send Later to download drafts that Thunderbird thinks are stored in that account simply hang forever. As a result, for users with accounts like this configured in Thunderbird, Send Later gets stuck on them and doesn't finish scanning all accounts for scheduled drafts.

I've addressed this in two ways:

1. I fixed Send Later so it no longer blocks forever when it can't read a message. This means that messages will be delivered _eventually_, but they may still be delivered slowly and later than expected if there are a lot of drafts that can't be read.
2. To make it possible to give users the ability to get rid of even those remaining delays, I've added an "Active accounts" section to the advanced Send Later preferences. Any account unchecked in that list of accounts will be completely ignored by Send Later, so even if the server is unreachable it won't delay Send Later's work.

Both of these changes are now available in release 10.1.4. To check what version of Send Later you have:

* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click on Extensions on the left if you're not already on the left if you're not already there.
* Find Send Later in the list of extensions and click on it to open its details page.
* The version number should be displayed there next to
"Version".

This release is not yet available for download from addons.thunderbird.net, but you can download and install it from its [GitHub release page](https://github.com/Extended-Thunder/send-later/releases/tag/v10.1.4) as follows:

* Download [this file](https://github.com/Extended-Thunder/send-later/releases/download/v10.1.4/send_later.xpi) to your computer. (If you are using Firefox, make sure to right click on the link and select
"Save Link As..." rather than just clicking on it, because otherwise Firefox will try to install it as a Firefox add-on.)
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click the gear icon at the top and select "Install Add-on From File...".
* Browse to and select the downloaded file.
* Click through the installation pop-ups.
* You can delete the downloaded file once you've installed it into Thunderbird.

Note that this is a prerelease. While we make every effort to ensure that prereleases are stable, they are a bit more likely to have bugs, so proceed with caution.

If you prefer to wait, the release will eventually be available on addons.thunderbird.net, and unless you've turned off automatic add-on updates, Thunderbird will eventually update to the new version automatically. To update immediately once it's available:

* Go to [addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/versions/) and confirm that release 10.1.4 is available for download there.
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click on Send later.
* Click the gear icon and select "Check for Updates".
* The add-on should update and then you should see the message, "Your add-ons have been updated," next to the gear icon.

I would greatly appreciate it if those of you who are still having this issue would try out this prerelease and post a comment here letting me know whether it solves your problem. If it _doesn't_ solve your problem, and you're willing to get on a Zoom with me to let me troubleshoot directly to try to figure out why, please email me at send-later-support@extended-thunder.org so we can make the necessary arrangements.

Thank you!

**Comment by jikamens** [comment] 2023-09-08 20:45
All of the causes of messages getting stuck in Drafts that I am aware of have been fixed. If you are running into this again please open a new issue.

**Closed by jikamens** 2023-09-08 20:45 UTC
