### ISSUE TITLE
open/close/open send later pop-up again, it's empty

### ISSUE THREAD

**Issue by jikamens** [Extended-Thunder/send-later#480] opened 2022-11-15 20:02 UTC
Version 9.2.2

Start composing a message.

Click the Send Later button.

Click it again to close the pop-up.

Click it a third-time. The pop-up is blank.

Blank pop-up appears to happen any time the pop-up is opened more than once in the same compose window.

**Comment by jph-sendlater** [comment] 2022-11-15 20:10
Appears to be a duplicate of #472 Will follow up in that issue thread

**Closed by jph-sendlater** 2022-11-15 20:10 UTC
