### ISSUE TITLE
Keyboard shortcut issues

### ISSUE THREAD

**Issue by Geremia** [Extended-Thunder/send-later#583] opened 2023-08-12 17:54 UTC
<kbd>Ctrl</kbd>+<kbd>Enter</kbd> makes the Send Later dialogue box pop up, but it does not trigger the "Send at" button when the box is open.

<kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>1</kbd> etc. and <kbd>Ctrl</kbd>+<kbd>1</kbd> etc. do not work (regardless of `“Send” does “Send Later”`). What's strange is that if I make a new message, don't specify a recipient or subject, and hit <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>1</kbd>, the "Invalid Recipient Address" dialog box pops up, but if I fill out the subject, body, and recipient address, <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>1</kbd> doesn't do anything.

<kbd>Ctrl</kbd>+Click and <kbd>Shift</kbd>+Click accelerator key do not work; the Send Later dialogue box pops up as if I wasn't holding <kbd>Ctrl</kbd> or <kbd>Shift</kbd> down.

<sub>I wonder if some of the above problems have to do with my my custom Xmodmap; `xev` says the key is "Return" (not "Enter"), and I've bound <kbd>ctrl</kbd> and <kbd>ctrl</kbd> to other keys.</sub>

I'm using Thunderbird 115.0.1 (64-bit) with Send Later 10.0.1 on Slackware64-current Linux (kernel 6.1.42), though I've had similar problems for awhile now with previous Thunderbird and Send Later versions. I've tried refreshing Thunderbird with the Troubleshooting Mode, but I still get the same problems.

**Comment by jikamens** [comment] 2023-08-12 22:51
Ctrl+Enter works for me in the pop-up, so I can't reproduce that issue. It seems like the first obvious troubleshooting step is to turn off your custom Xmodmap and reboot so that you're using a stock keyboard and then check if the problem persists.

Also, just to clarify, what exactly do you mean when you say you've bound ctrl to other keys? Can you include your Xmodmap file here or something so I can see exactly what you're doing, which may help me to reproduce this?

I _can_ reproduce the problem that Ctrl-Alt-1 isn't working in the compose window, so I am looking into that. I am also able to reproduce that Shift-Click and Ctrl-Click on the Send Later button in the compose window are not doing what they're supposed to, so I'm looking into that as well.

**Comment by Geremia** [comment] 2023-08-12 23:02
@jikamens The only thing [resetting the Xmodmap](https://askubuntu.com/a/980201/362789) fixed was that <kbd>Ctrl</kbd>+<kbd>Enter</kbd> triggers the "Send at…" button in the SendLater popup dialog box.

**Comment by jikamens** [comment] 2023-08-12 23:25
OK I have found and fixed both the issue with Ctrl-click and Shift-Click on the compose window button, and the issue of Ctrl-Alt-1, -2, and -3 not working in the compose window. If you can post your Xmodmap here (or email it to me at send-later-support@extended-thunder.org) I will see if I can figure out how to reproduce and the the issue your having of Ctrl-Enter in the pop-up not doing the right thing when you've rebound your keyboard.

**Comment by jikamens** [comment] 2023-08-18 11:44
All of the problems in this issue are resolved in the recently released version 10.0.2.

**Closed by jikamens** 2023-08-18 11:44 UTC
