### ISSUE TITLE
"Send Later" column spontaneously appearing in folders that are *not* the Drafts folder

### ISSUE THREAD

**Issue by jikamens** [Extended-Thunder/send-later#99] opened 2020-11-10 12:30 UTC
With the current trunk (not 8.1.0 branch), I'm the Send Later column spontaneously appear sometimes -- but not every time -- when I view some folders that aren't my Drafts folder.

**Comment by jperryhouts** [comment] 2020-11-15 21:20
It's not quite the same thing, but [this Thunderbird bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1609378) talks a bit about how column handling can be inconsistent with mixed webextension / experiment addons. Seems like the order in which column handlers are called is not predictable. This is coupled with the fact that removing the column handler usually fails when the addon is uninstalled or updated, which means that there can end up being multiple copies of the column handler callback hanging around, executing in an unpredictable order. None of that mess guarantees that things will not work as intended, but it definitely increases the likelihood of erratic behavior.

I added a fallback in #114, which sets a timeout to re-check the column visibility state after that initial cluster f\*k of handlers has settled down. However, this workaround is also used by Thunderbird Conversations, and likely other addons as well, which just creates the opportunity for a second cluster f\*k of addon handlers executing code a moment after the folder view is loaded.

Eventually there will be a [webextension friendly way of doing this](https://bugzilla.mozilla.org/show_bug.cgi?id=1615801), but in the mean time hopefully this kludge makes the column visibility issue a little more manageable. I'm closing this issue for now, but obviously open it back up if this bug persists.

**Closed by jperryhouts** 2020-11-15 21:20 UTC
