### ISSUE TITLE
Send Later 9.0.6 Not Functioning in Thunderbird 91.2.1

### ISSUE THREAD

**Issue by tod1938** [Extended-Thunder/send-later#396] opened 2021-11-02 21:30 UTC
Win10 x64, auto update
ThunderBird x32, auto update, no other add-ons
I have been using Send Later for several months without issue.
Shortly after the TB 91.2.1 update, TB started to crash.
Starting TB in Troubleshoot Mode (disabling Send Later) prevents the crashes.
I re-installed both TB and Send Later.
They worked fine for 2 days then started crashing again.

**Comment by Aquaritone** [comment] 2021-11-04 14:04
There is a bug in Thunderbird that is currently being fixed. You can try this for now. It comes from the conversation among the programmers and has worked for me:

1. Disable all your add-ons and restart Thunderbird (I don't know that this is necessary but it doesn't hurt).
2. Go to Preferences/General/Offline (toward the bottom of the screen).
3. Uncheck "Automatically follow detected online state."
4. Under "Manually state when starting up:" clicked the button
        next to "Online"

Re-enable your add-ons and give it a try,

**Comment by jph-sendlater** [comment] 2021-11-20 17:29
That definitely could be the issue here. If it is the cause, then it should be fixed in Thunderbird 91.3.1 without any action on your part. Let me know if it's not fixed after that.

**Comment by jph-sendlater** [comment] 2022-02-05 21:16
Closing this as I haven't heard anything about it in quite a while

**Closed by jph-sendlater** 2022-02-05 21:16 UTC
