### ISSUE TITLE
Not processing second outgoing email

### ISSUE THREAD

**Issue by drkenrich** [Extended-Thunder/send-later#65] opened 2020-11-02 20:54 UTC
I must be doing something wrong, but then I'm not good at programming.

I use TB 68 instead of the updated one because of other issues. I have both _send_later-7.4.4-tb.xpi_ and _send_later-8.0.11-tb.xpi._ I couldn't find the Send Later menu button until I removed 8 and installed 7. Then it seemed to work.

The first email was to go to me plus a List 1 with 8 emails. The second was scheduled for 8 more 2 hours later. Following the first it took about 60 seconds to time out with some message about maybe not working. However, instead of sending immediately, it just put it in my outbox. The second never did anything, not even posting to the outbox.

What am I doing wrong?

**Comment by jperryhouts** [comment] 2020-11-02 21:08
I'm surprised Thunderbird let you install both. They should be mutually incompatible -- i.e. version 7.x is compatible with Thunderbird <=68, and version 8.x is compatible with Thunderbird >=78.

I can't speak to issues with the 7.x branch, but I do suggest that when you upgrade to Thunderbird 78 you install the latest beta release ([8.0.15](https://github.com/Extended-Thunder/send-later/releases/tag/8.0.15-rc2) as of today).

One trivial thing that might help would just be restarting Thunderbird after changing Send Later versions. Beyond that I'll defer to @jikamens about 7.x branch issues.

**Comment by jikamens** [comment] 2020-11-02 22:11
First of all, putting messages in your Outbox is how Send Mail works. It puts the messages into your Outbox and then tells Thunderbird to deliver them from there, unless you've told Send Later not to do that. Check your Send Later preferences and see if you've disabled the "Trigger unsent message delivery from Outbox" checkbox. If you have, then that's why the messages weren't sent once they were put into your Outbox -- you told Send Later not to send them.

If that checkbox is checked, then the problem is that Thunderbird was unable to deliver them for some reason. That's a Thunderbird issue, not a Send Later issue. What happens to the messages in your outbox when you execute the "File | Send Unsent Messages" menu command?

I do not understand what "Following the first it took about 60 seconds to time out with some message about maybe not working" means. That is too vague for me to draw any meaningful conclusions from it. It's not clear exactly what "timed out" or when, you haven't told us exactly what the error message was, and you haven't included a screenshot of the error message. For us to be able to provide any help with that you're going to have to provide us with more details about what went wrong. Try reproducing the issue, and if you're able to do so, then tell us exactly what timed out and what the error message said or send a screenshot.

Please note that there is an extensive [section in the send later user guide](https://blog.kamens.us/send-later/#outbox) about how to troubleshoot fail to send issues.

**Comment by bome** [comment] 2020-11-02 22:47
> putting messages in your Outbox is how Send Mail works
When I started using the v8 beta versions, I unchecked the option "Trigger unsent message delivery from Outbox", because I did not want _Send Later_ to interfere with my Outbox at all. I didn't know that's how it works now. It didn't take me long to find out that Send Later was merely placing emails into the Outbox and sending them, so I enabled that option and happy ever since.

So, in order to avoid that for other people like me, I suggest reformulating this option. For example "[x] After moving delayed messages to Outbox, automatically send all queued messages in Outbox". Or, negate the logic: "[ ] Keep delayed messages in Outbox and do not send them automatically".
Actually, for the least confusion, I would just remove the option entirely.

**Comment by drkenrich** [comment] 2020-11-03 00:17
Wow, fast responses. Thanks.

First in order of comment,
I uninstalled one version before I installed the other and restarted T-Bird several times.

This time I took the time to take screenshots along the way.
Not thinking properly and relying on FF and Chrome experience I kept looking for options on the Add-on listings. Not until I couldn't find any and dug deeper did I find the Add-on Options menu. Then I could start. **Send-Later Preferences** shows how they are set. **Unsent Messages** shows the messages, folder and message before I did a new test. I tried to click on File > Send Unsent Messages, but everything was grayed out and didn't work. I did a new send shown in **Send Later Menu** but all it did was put it in the Outbox folder again shown in **Unsent Messages-2**. Finally, after a delay the **Error Message** came up.

Where do I go from here? I hope it's not a reinstall of TB. I just did that about 2 weeks ago.


![Send-Later Preferences](https://user-images.githubusercontent.com/34901309/97932646-6a56c900-1d25-11eb-8811-dc16a2540c5d.jpg)
![Unsent Messages 2](https://user-images.githubusercontent.com/34901309/97932648-6aef5f80-1d25-11eb-9eca-74370f57e135.jpg)
![Unsent Messages](https://user-images.githubusercontent.com/34901309/97932649-6aef5f80-1d25-11eb-87aa-4ca0df60e712.jpg)
![Error Message](https://user-images.githubusercontent.com/34901309/97932650-6b87f600-1d25-11eb-8bbc-839caaffde15.jpg)
![Message Filters Panel](https://user-images.githubusercontent.com/34901309/97932656-6cb92300-1d25-11eb-91a0-14b9d144e17b.jpg)
![Send Later Menu](https://user-images.githubusercontent.com/34901309/97932657-6d51b980-1d25-11eb-98cc-ffb468fea244.jpg)

**Comment by jikamens** [comment] 2020-11-03 00:21
Did you go to the link referenced in the error message and follow the troubleshooting instructions found there?

**Comment by jperryhouts** [comment] 2020-11-03 00:23
Sorry, I hadn't meant to close this issue so soon.

**Comment by drkenrich** [comment] 2020-11-03 00:28
Sorry I forgot to answer the troubleshooting guide. Yes, I did, as far as Test #1, but I wasn't sure what my result meant.

**Comment by jikamens** [comment] 2020-11-03 00:40
How do you expect me to help you further if you say that you weren't sure how to interpret the result of the test but you don't tell me what the result was so I can help you interpret it?

This is in the same vein as your earlier comments: how did you expect me to help you if you told me there was an error message but didn't tell me what the error message was?

Do you understand that in order for me to be able to help you, you have to provide me with DETAILED INFORMATION about what's happening and what's going wrong? I'm asking because your interactions here so far seem to suggest that you don't understand this, which is somewhat puzzling, since it seems like it's something that's pretty darn obvious.

I don't want to have to keep pulling information out of you bit by bit, which feels like pulling teeth. Therefore, you get one more chance to be COMPLETELY FORTHCOMING in responding to my inquiries, and if you blow it again, I'm out. Whether @jperryhouts chooses to continue supporting you is his call, but as for me, I am already full up in my life with things and people wasting my time and causing me angst, so I'm going to opt out of yet another one.

So, look. Test #1 has four steps in it. After those four steps, the test asks whether you got an error. Did you get an error, or not? If you DID get an error, then the test says exactly what the four possible problems are, and tells you how to fix all of them. So, did you follow those steps? If you did NOT get an error, then you're supposed to continue on to Test #2 in order to further narrow down what's going wrong. Did you do that? If not, why not?

I didn't write the troubleshooting instructions in the user guide because I like to hear the sound of my own keyboard. I wrote them because they capture literally EVERYTHING I KNOW about troubleshooting this issue, and I don't want to have to spend my time guiding people through the same troubleshooting steps over and over and over again, so I wrote them down, in detail, with a clear roadmap of the order in which to do things, so that people could troubleshoot and reach conclusions themselves.

Run the tests. Follow the instructions in them. Don't contact me again unless you've done all of them and you're still having a problem.

**Closed by jikamens** 2020-11-03 00:40 UTC

**Comment by drkenrich** [comment] 2020-11-03 00:55
Jeez, what a grouch.

Did the test again. Result = _If the “Send Unsent Messages” command is grayed out in the menu, i.e., you cannot execute it even though there is a message in the Outbox, or if the message does not send successfully when you execute this command, ,then Send Later is not the problem._ 

Checked Test #1 again, just like the first time and
_corrupt Outbox folder — see below for how to repair it;_ = **Fixed as per your instructions**
_full Windows temporary directory — see below for how to repair it;_ - **Temp directory empty and always kept that WAY.**
_your hard disk is full; or_ = **No, LOTS of room an 15TB of disks.**
_something is broken in your Thunderbird profile — unfortunately the only way I’ve been able to find to resolve this is to migrate to a new Thunderbird profile and get rid of the old one._ = **Hence my previous comment of hoping it's not going to require a reinstall of T-Bird.**

So, all the above were the results I arrived at BEFORE your tirade and I was hoping there was some other answer.
