### ISSUE TITLE
Messages in various folders suddenly get the subject of schedules messages

### ISSUE THREAD

**Issue by jurgenhaas** [Extended-Thunder/send-later#496] opened 2022-12-13 17:23 UTC
I'm using Thunderbird 102.6.0 on Ubuntu 20.04 and SL 9.2.4

When I prepare a message and schedule it for being sent later, I see that red number on the "Send later" icon and the message is in the drafts folder. So far so good.

But when navigating through folders in Thunderbird, some of the messages there suddenly get the subject line of that scheduled message. And that wrong subject line doesn't go away anymore. However, when I open the message source of such a mis-handled message, then the subject line there is OK.

I'm sure this is because of this plugin, because it only started yesterday, when I installed this plugin and it only happens, while a message is being scheduled waiting for being sent. Never otherwise and I'm using TB intensively all day.

Any idea where this could be coming from?

**Comment by jurgenhaas** [comment] 2022-12-14 08:44
And even worse: I just learned that the scheduled emails got delivered encrypted and are completely useless.

**Comment by jph-sendlater** [comment] 2022-12-24 01:28
I've never heard of that issue happening before, and it's a bit mystifying how it could be possible.

The second issue is related to #200 and can probably be solved with the same fix, although send later should have caught it earlier and not sent the encrypted message.

I'll look into both when I get a chance.

**Comment by jikamens** [comment] 2023-07-22 18:54
@jurgenhaas are you still seeing the issue you described with subject lines getting overwritten weirdly with scheduled message subject lines? That sounds a lot like something is getting corrupted inside Thunderbird; it's hard to imagine how this could be a Send Later issue (though not impossible).

**Comment by jurgenhaas** [comment] 2023-07-24 06:57
@jikamens I have removed that add-on many months ago, as it was a real mess. I won't go back top try again, can't afford that for now.

**Comment by jikamens** [comment] 2023-07-24 14:55
There was a gap in responsive support for the add-on but we are in the process of rectifying it. If you want to give it another try and work with me to figure out what was going wrong for you and get it fixed, I am happy to do that. However, if you aren't able to do that then there's nothing I can do about this issue, since no one else has reported it and I cannot reproduce it, so I am closing the issue. If you want to work with me to troubleshoot it further, feel free to reopen.

**Closed by jikamens** 2023-07-24 14:55 UTC
