### ISSUE TITLE
International Date format confusion (Irish timezone)

### ISSUE THREAD

**Issue by RealRaven2000** [Extended-Thunder/send-later#575] opened 2023-08-09 14:36 UTC
While reviewing your Add-on for atn I noticed the following quirk. When I try to edit the time on the default (suggested) future date, there is some inconsistency happening, maybe cause by MM/DD/YYYY  formatting:

![image](https://github.com/Extended-Thunder/send-later/assets/6314674/923aede7-aeac-4e76-b766-4ec47e04c6be)

I only wanted to edit the time, but this sets the send later date to 30 days ahead in the future. So I guess the current date 08/09/2023 - the 9th of August 2023 (which is autofilled by SL) seems to be also interpreted as 8th of september.

If I use the date picker, it looks like this:
![image](https://github.com/Extended-Thunder/send-later/assets/6314674/6233c1fb-4312-4148-a09f-5dd7fecc87b5)

I am using an en-US Thunderbird version, but I am in the BST (British Summertime) timezone and my system is configured for en-UK dates  (DD/MM/YYYY)

**Comment by jikamens** [comment] 2023-08-09 15:03
Duplicate of #429.

**Closed by jikamens** 2023-08-09 15:03 UTC
