### ISSUE TITLE
The date/time setting window after opening Send Later is now narrow and needs resizing every time

### ISSUE THREAD

**Issue by barnez** [Extended-Thunder/send-later#723] opened 2024-07-28 06:11 UTC
### Prerequisites

- [X] I am reporting a problem, not asking a question (for questions, go to [Discussions](https://github.com/Extended-Thunder/send-later/discussions)).
- [X] I have consulted the [user guide](https://extended-thunder.github.io/send-later/).
- [X] I have confirmed that I'm running the current version and the problem persists there (note the version number in fine print next to the add-on name [on addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/) and compare it to the version number listed in the add-on details opened from the Add-ons page in Thunderbird; if you've got an old version, click the gear icon and select "Check for Updates").
- [X] If I'm having an issue with date-parsing confusion, I've read the [section about that in the user guide](https://extended-thunder.github.io/send-later/#date-format-confusion-in-the-scheduler-pop-up) and I still think this is something different.
- [X] If I'm having an issue with messages not being delivered, I've followed the [troubleshooting steps in the user guide](https://extended-thunder.github.io/send-later/#messages-dont-send-or-send-multiple-times) and it's still an issue.

### Describe the bug

On selecting "Send Later" to open the new window and set the date and time to send, as of today the window is now narrow and needs re-sizing to be able to enter the date. This is the only add-on enabled in Thunderbird. Resizing the window, closing and re-opening Thunderbird/Send Later does not help.

<img width="960" alt="send later" src="https://github.com/user-attachments/assets/a22a8368-5792-4e3c-b420-bb9e989412d6">

### How to reproduce

1. Click on "New Message".
2. Select "Send Later".

### Expected behavior

The Send Later window should be sized proportional to the Thunderbird window, and/or it should remember any re-sizing the next time the Send Later window is opened.

### Operating System

Windows 11 Pro

### Operating System Version

23H2, Build: 22631.3880

### Thunderbird version

115.13.0 (64-bit)

### Send Later start-up string

Send Later version 10.5.1 on Thunderbird 115.13.0 (20240715172621) [win x86-64] UI locale en-GB, Date Locale en-GB

**Comment by jikamens** [comment] 2024-07-28 21:56
This is a duplicate of #700.

**Closed by jikamens** 2024-07-28 21:56 UTC
