### ISSUE TITLE
Thunderbird 102.7.0 + Send Later makes program ignore CTRL+ENTER confirmation window

### ISSUE THREAD

**Issue by Balls0fSteel** [Extended-Thunder/send-later#521] opened 2023-01-26 18:48 UTC
So let me start with this: This is a new issue, it wasn't like this before.

Basically, if you have to Send Later enabled, Thunderbird will NOT show the Send Confirm dialog. I have verified that the relevant option in GUI and config editor is set - and the dialog is only ignored if this addon is enabled.

I think the last Thunderbird update, or the one before broke something in addon functionality.

Let me know if I can help test this any way.

**Comment by jikamens** [comment] 2023-07-22 19:05
Duplicate of #494.

**Closed by jikamens** 2023-07-22 19:05 UTC
