### ISSUE TITLE
option to turn off 'Send Later in Status Bar' not working

### ISSUE THREAD

**Issue by cooch17** [Extended-Thunder/send-later#309] opened 2021-04-09 14:51 UTC
Am using TBird 78.9.x, under Windows (10) and various GNU/Linux distributions. For any of the installs, I am unable to 'turn off' the option to 'Show Send Later in Status Bar'.  If I check/uncheck this option, the 'Send Later [idle]' temporarily disappears from the status bar. But, not permanently -- if I close and restart TBird, it comes back.

image1.jpg (attached) shows the Send Later configuration. image2.jpg (attached) shows that the 'Send Later [Idle]' indication is still in the status bar, after restartint TBird.  The only way I can remove it is to check/uncheck the box in Send Later config -- and then, it is removed from the status bar until I close and restart TBird, at which point, it returns again (even though it remains 'unchecked' in the Send Later config). 

If it maters, on all of the systems I used, I upgraded from TBird 68 -> 78, with the compatible add ons being upgraded in the process. Perhaps there is something residual left behind for Send Later that is causing the problem. I tried deleted and re-installing Send Later, but that didn't solve the problem. 
![image1](https://user-images.githubusercontent.com/4500611/114198594-81779380-9921-11eb-8d58-0ea46a79e9a9.jpg)
![image2](https://user-images.githubusercontent.com/4500611/114198595-81779380-9921-11eb-846f-449e55fdd7ff.jpg)

**Comment by jph-sendlater** [comment] 2021-04-09 16:36
Does this happen every time you restart Thunderbird, or only sometimes. I haven't been able to reproduce this behavior on Thunderbird 78.7.

**Comment by cooch17** [comment] 2021-04-10 21:23
Every time. The only thing in common is that on all my machines, I did an in-place upgrade from 68 -> 78.x.  (I'm on 78.9.1). I'm willing to bet that because I did an upgrade, which also upgrades add-ons (I believe), then something in the upgrade process broke something. I suppose I could uninstall SendLater, and then look for any remants of the add-on, and then re-install.  Or, fire up a virtual machine, install some flavor of Linus, install TBird 'fresh', and then try SendLater.  Because this happens consistently on only 4 of my 'main machines', some Windows, some Linux, I'm looking at 'in place upgrade' as the only common factor. 

Either way, it isn't a huge deal, but, the add-on is most definitely ignoring the add-on preference to not show itself in the status bar. It *does* 'go away' temporarily if I check 'show in status bar' and then un-check it, but...preference doesn't stick.

**Comment by jph-sendlater** [comment] 2021-04-10 21:38
Hm. I also used the in-place upgrade to version 78, and I imagine most other people did too. I'm thinking this isn't directly related to your setup, but rather some sort of race condition during start up. Maybe the status bar components are being initialized before the user preferences are available to them or something similar. Thunderbird is transitioning to a multi-process architecture soon, and I've been told that might start causing problems with add-ons that operate partially outside of the extension sandbox (as is the case for that specific part of Send Later).

I'm going to be out of town this coming week, but I'll look into this when I get back.

**Comment by cooch17** [comment] 2021-04-10 21:41
Could be. What I'll do at some point this week is video record the desktop as the bug happens -- I have a YouTube channel where I post 'bugs & issues' videos, so that devs can actually see the problem. This is often very helpful, since it avoids having to interpret a ;anguage-based description of what happens.

**Comment by jph-sendlater** [comment] 2021-04-11 02:21
You mentioned that the status bar item goes away if you toggle its checkbox in your preferences, but would it also go away if you toggle a *different* setting? That is, does it respond when any setting is updated, or only that one?

**Comment by cooch17** [comment] 2021-04-11 11:22
Yes, in fact. Not something I'd tried before. For example, if I toggle 'Mark scheduled drafts as read', the status bar item disappears. At least, until I close and re-start TBird.

**Comment by jph-sendlater** [comment] 2021-04-11 14:42
Good to know. Whenever any setting is changed it triggers the status bar to reset based on the current configuration. That means the problem is something about the sequence in which it initializes itself. I won't have a chance to look into this until at least next weekend, but that gives me a good starting point. thanks!

**Comment by jph-sendlater** [comment] 2021-04-21 21:37
I've fixed this along with a major restructuring of the way send later creates UI components, which will be part of [version 8.9](https://github.com/Extended-Thunder/send-later/releases/tag/8.9.0). I plan to leave that version in beta status for longer than usual to help ensure that I haven't broken anything in the process.

**Closed by jph-sendlater** 2021-04-21 21:37 UTC

**Comment by jph-sendlater** [comment] 2021-05-19 01:01
FYI for anyone who's following this issue:

The patch that fixed this issue caused mysterious side effects for some users-- namely, the draft folder column in the UI stopped working.

I'm currently focusing my effort on targeting the upcoming version of Thunderbird, so instead of picking apart the changes that fixed this from the ones that broke the draft folder column I just reverted the whole patch.

The fix for this issue is still included in Send Later's development branch, which is only compatible with Thunderbird versions > 88.

Sorry for the inconvenience in the mean time.
