### ISSUE TITLE
Compatability with one click "send later" button

### ISSUE THREAD

**Issue by djbirke** [Extended-Thunder/send-later#100] opened 2020-11-10 18:43 UTC
First, I love this add-on. Thank you for all the work that goes into making it.

Before upgrading to TB 78, I used the add-on together with [Send Later Button](https://addons.thunderbird.net/en-US/thunderbird/addon/send-later-button/reviews/). This allowed me to do a single button-click and have the email scheduled immediately scheduled to be sent in 3 minutes (without the pop-up dialog that occurs by default in Send Later).

However, the compatibility with Send Later Button seems to be broken in TB 78.

Could the one click feature be restored in TB 78? Maybe even without the need for an extra add-on?

**Comment by jperryhouts** [comment] 2020-11-10 18:58
This is on my radar, but I don't yet know if it will be possible to fix. It is probably possible to regain compatibility with the "Send Later Button" addon, but I need to look into that further. The ability to add additional toolbar shortcut buttons is unfortunately not possible with a single addon. That is by design, so I expect Thunderbird will not choose to support that in the future. The new add-on system is designed to force extensions to be as unobtrusive as possible, and limiting each one to a single toolbar button is one way they've done that.

All that said, you can still configure similar behavior by setting "Send delays message by ___ minutes" in the Send Later preferences. That will block ordinary send operations, which might not be what you want, but it will have the same effect as a dedicated button.

**Comment by ribz** [comment] 2020-11-10 19:05
Can you trap things like modifier keys been pressed at the same time as the button? Akin to how pressing Shift when creating a new email creates an HTML email rather than plain text, if plain text is the default for that account.

That way you could make it so that Shift+Send Later does a 'default' action - such as delay by 3 mins (or indeed have a setting to invert the situation, so that the shift modifier allows normal usage)

**Comment by jperryhouts** [comment] 2020-11-10 19:14
That's a great idea. I hadn't been aware of it, but it looks like that is possible. This will have to wait until after the next release, but shouldn't be hard to implement.

**Comment by djbirke** [comment] 2020-11-11 00:33
Thank you both for the fast responses.

@jperryhouts, you are right, sometimes I really need to send that email _now_ and so the extra configuration does not work for me.

@ribz, your idea is brilliant, I would love to have "Shift+Send Later" to correspond to sending immediately.

Thank you again for your amazing work!

**Comment by jperryhouts** [comment] 2020-11-23 03:31
Well, this is disappointing. After writing the whole patch to enable this and it not working, I found this super obvious text in the documentation:

> onClicked(tab, [info])
    Fired when a toolbar action icon is clicked. **This event will not fire if the toolbar action has a popup.**

I tried working around it, but unfortunately it doesn't look like that's going to be possible. I opened a [bugzilla report](https://bugzilla.mozilla.org/show_bug.cgi?id=1678967) about this, but I expect this was an intentional choice on the part of the Thunderbird developers, and they might reject that proposal outright.

@djbirke If you use a send delay more frequently than not, you can always set the 'send delays messages ...' option, and then click through the popup dialog when you do want to send now -- the 'send now' button of course skips any such delays.

Sorry this is a disappointing conclusion, but I'm going to close this issue for now until the Thunderbird devs make movement on their end one way or another.

**Closed by jperryhouts** 2020-11-23 03:31 UTC
Labels: enhancement

**Comment by djbirke** [comment] 2021-04-10 23:45
@jperryhouts did the suggested workaround from the Bugzilla report change anything in terms of feasibility?

**Comment by jph-sendlater** [comment] 2021-04-11 14:57
I haven't gotten around to trying it yet. I'll get to dedicate a little more time to Send Later next week and I'll see what I can do about it then.

**Comment by jph-sendlater** [comment] 2021-04-18 19:00
This is now implemented via 5c9b550a369a64591af1d3f81481a7e9b2820889 and will be part of the next beta release. There are options for customizing the behavior of the compose action button when holding shift or ctrl (cmd on macos). By default they are as follows:

> Regular click: Regular behavior -- opens the scheduler dialog
Ctrl+Click: Delay message 5 minutes
Shift+Click: Send during business hours

Those behaviors can be modified in the options dialog in the same way the quick-shortcut keys can be modified.

**Comment by djbirke** [comment] 2021-04-20 03:39
This sounds fantastic. Thank you once again for all your work on this add-on, @jph-sendlater!
