### ISSUE TITLE
Messages not sent

### ISSUE THREAD

**Issue by ipante** [Extended-Thunder/send-later#282] opened 2021-01-15 11:52 UTC
Hi there. 

I'm using Thunderberd 78.6.1 for Mac with the latest send-it-later plugin with an exchange account. At the end of the installation, I get this alert from the send later plugin : "TypeError : compactedDrafts is undefined". 

<img width="386" alt="Capture d’écran 2021-01-12 à 16 20 57" src="https://user-images.githubusercontent.com/1324037/104724187-9f719580-5730-11eb-90d4-83802acd37a3.png">

This alert apart, the installation looks complete : the button and popup are there, and scheduled mail are stored into the "drafts" folder with the right time of expedition. But at the due time, nothing is sent. I've got the same result with two other colleagues. We were aware to keep the app open during all the process.

I would be happy to try your suggested fixes.

**Comment by jph-sendlater** [comment] 2021-01-15 16:23
Interesting. This could happen if there was a problem accessing the Draft folders, but it could be a number of other things as well.

Has Thunderbird been running since you installed it / got this error? If so: try opening the error console (Cmd+Shift+J) Then right click (cmd+click on mac?) and do "Export visible messages to > File", then send that file to me at send-later-support@extended-thunder.org

That would certainly be a start, and we'll see where it takes us. Thanks!

**Comment by ipante** [comment] 2021-01-15 19:49
Error console log sent. Many thanks for your help!

**Comment by ipante** [comment] 2021-01-23 13:53
Is the log useful?

**Comment by jph-sendlater** [comment] 2021-01-23 15:36
Yes, I'm really sorry for the delayed response, but I've had a crazy couple weeks with work. I still don't have a good answer for you, but I'll have a chance to look more closely at the log this weekend.

**Comment by ipante** [comment] 2021-01-23 17:56
Don't worry, it's absolutely fine! Your help is very much appreciated, but take your time ;)

**Comment by jph-sendlater** [comment] 2021-01-24 16:23
Question: Does the status bar menu show a number for how many messages are pending? e.g. It should say something like:  
`Envoyer Plus Tard [EN ATTENTE 7]`  

There's nothing in your log file that indicates any actual errors are occurring, but one thing I notice is that you're using an OWL account, which is known to be finicky, so it may be causing problems. You could try changing your account's Drafts folder to the 'Local Folders/Drafts' (via `Account settings` > `Copies and Folders` > `"Store Draft messages in ..."`). Then any future messages you schedule will be stored locally, and Send Later will not need to interact with the Exchange server directly. That obviously wouldn't be a proper solution, but if it does fix the issue for you, then I would need to look into why Send Later is misbehaving with OWL.

**Comment by ipante** [comment] 2021-01-24 20:27
Hello there,

I'll answer directly in your message.

Le 24 janv. 2021 à 17:23, jph-sendlater <notifications@github.com<mailto:notifications@github.com>> a écrit :



Question: Does the status bar menu show a number for how many messages are pending? e.g. It should say something like:
Envoyer Plus Tard [EN ATTENTE 7]

Absolutely right, I got this message.

There's nothing in your log file that indicates any actual errors are occurring, but one thing I notice is that you're using an OWL account, which is known to be finicky, so it may be causing problems. You could try changing your account's Drafts folder to the 'Local Folders/Drafts' (via Account settings > Copies and Folders > "Store Draft messages in ...").

That way, right?

[cid:D6188F15-24CB-431D-BD74-66A580340FF1]


Then any future messages you schedule will be stored locally, and Send Later will not need to interact with the Exchange server directly. That obviously wouldn't be a proper solution, but if it does fix the issue for you, then I would need to look into why Send Later is misbehaving with OWL.

Hmm, sadly it changes nothing. Messages are just added to the pending ones.

Many thanks for your help!

**Comment by jph-sendlater** [comment] 2021-01-24 20:35
@ipante it looks like you attached an image, which didn't come through via the github email proxy.

**Comment by ipante** [comment] 2021-01-24 21:39
Yes, sorry. It was a capture of my settings.

I selected "Keep Message archives in : "Archives" Folder on : Dossiers locaux"

But those settings doesn't solve the issue, sadly :(

Le 24 janv. 2021 à 21:35, jph-sendlater <notifications@github.com<mailto:notifications@github.com>> a écrit :



@ipante<https://github.com/ipante> it looks like you attached an image, which didn't come through via the github email proxy.

**Comment by jph-sendlater** [comment] 2021-01-24 23:31
It may be a translation problem, but there should be a separate setting for "Keep Draft messages in: ..." Something like the second item down in this screenshot:

![image](https://user-images.githubusercontent.com/75693008/105647220-e9592a80-5e58-11eb-8c62-4f059e68c64b.png)

You would want to change that to `"Drafts" folder on: Local Folders`

**Comment by ipante** [comment] 2021-01-25 05:33
<img width="782" alt="Capture d’écran 2021-01-25 à 06 33 03" src="https://user-images.githubusercontent.com/1324037/105665406-47c4ee00-5ed7-11eb-8afd-965f1960c198.png">

**Comment by 0x90shell** [comment] 2021-03-04 12:37
I had the same issue come up using OWL plugin, but I'm not sure if it's a real issue. Clicking OK, Send Later will detect pending messages still andl notify with PENDING # status. Send Later doesn't seem to know how to mark unread or send via the OWL account draft folder, though.

The emails not being sent is succinctly explained in the [manual](https://extended-thunder.github.io/send-later/#owl-for-exchange-add-on). Thunderbird's outbox doesn't know how to use OWL and most OWL users aren't going to have SMTP setup.  I confirmed it would send by local + smtp, but that isn't viable in most professional settings.

**Comment by jph-sendlater** [comment] 2021-03-04 16:08
@0x90shell I believe the usual behavior in that case would be that the messages get deposited into the outbox, but they do not get sent, but I could be wrong about that. Is that what you observe without smtp?

@ipante Just to confirm that is not what you're experiencing. It sounds like in your case the messages remain in the drafts folder, and do not get moved into the outbox at all. Correct me if I'm wrong about that.

**Comment by 0x90shell** [comment] 2021-03-06 06:27
In my case, they remain in the draft folders. If in local draft they will be marked read using the defaults, but in O365/exchange draft they will not be marked unread. The status shows pending regardless of folder, but they only get sent if an outgoing SMTP is used. I'll look more into this next week to confirm.

**Comment by jph-sendlater** [comment] 2021-04-28 16:09
Sorry for the radio silence, but I haven't figured out anything new about this bug. I've been working with another user on tracking down something similar, and in that case it seems to be related to a bug in Thunderbird related to IMAP folders with a "%" character in their names: https://bugzilla.mozilla.org/show_bug.cgi?id=1707408

Do you happen to have any folders like that? If so, is it possible for you to rename them at least temporarily to see whether that might solve the problem?

**Comment by jph-sendlater** [comment] 2021-05-07 17:44
I'm going to close this issue for now since i haven't heard back in a bit, but let me know if this is still affecting you and I'll open it back up.

**Comment by jetm** [comment] 2021-05-07 21:39
@jph-sendlater I continue having the same problem. The message is never sent later. The message is saved in the Draft folder. I am using a Microsoft Exchange account with Owl for Exchange extension. I have followed the instructions for this extension without success. Any information I could provide to debug it further?

**Comment by jph-sendlater** [comment] 2021-05-09 19:05
@jetm Do you happen to have any directories with '%' characters in their names?

**Comment by jetm** [comment] 2021-05-10 23:26
@jph-sendlater I check all the folders, and they don't have a '%' character.

**Comment by 0x90shell** [comment] 2021-07-21 16:20
No longer using same email, but in my case there was no "%" chars in the folder names.

**Comment by jph-sendlater** [comment] 2022-11-13 22:29
Closing this because it hasn't been touched in so long. If it's still an issue please open a new ticket.

**Closed by jph-sendlater** 2022-11-13 22:29 UTC
