### ISSUE TITLE
Follow Thunderbird Color Scheme

### ISSUE THREAD

**Issue by anishmittal2020** [Extended-Thunder/send-later#439] opened 2022-04-04 13:06 UTC
Current: (Text is unreadable in the options page)

![image](https://user-images.githubusercontent.com/42092626/161551292-074b9dd0-2b43-413b-9d68-ea6b2fb4cbb2.png)

Follow Thunderbird Color Scheme:

![image](https://user-images.githubusercontent.com/42092626/161550088-b36a9eab-86f1-400f-85c1-ab379623fd51.png)

**Comment by jph-sendlater** [comment] 2022-04-17 02:43
This is an issue with some linux display managers, and is caused by code in Thunderbird itself, not in Send Later. Incidentally, I believe the problem was inherited from Firefox. Good news is that it's fixed in the latest Thunderbird version. Sorry I don't recall which version number the fix happened in. I'm on the beta branch, and it happened a while ago. Hopefully that version trickles its way down to most package managers soon.

**Closed by jph-sendlater** 2022-04-17 02:43 UTC
