### ISSUE TITLE
The Send Later box immediately dissapears after appearing.

### ISSUE THREAD

**Issue by Geremia** [Extended-Thunder/send-later#729] opened 2024-09-12 22:51 UTC
### Prerequisites

- [X] I am reporting a problem, not asking a question (for questions, go to [Discussions](https://github.com/Extended-Thunder/send-later/discussions)).
- [X] I have consulted the [user guide](https://extended-thunder.github.io/send-later/).
- [X] I have confirmed that I'm running the current version and the problem persists there (note the version number in fine print next to the add-on name [on addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/) and compare it to the version number listed in the add-on details opened from the Add-ons page in Thunderbird; if you've got an old version, click the gear icon and select "Check for Updates").
- [X] If I'm having an issue with date-parsing confusion, I've read the [section about that in the user guide](https://extended-thunder.github.io/send-later/#date-format-confusion-in-the-scheduler-pop-up) and I still think this is something different.
- [X] If I'm having an issue with messages not being delivered, I've followed the [troubleshooting steps in the user guide](https://extended-thunder.github.io/send-later/#messages-dont-send-or-send-multiple-times) and it's still an issue.

### Describe the bug

This occurs when clicking the <kbd>Send Later</kbd> button:
![out-2024-09-12_15 44 19](https://github.com/user-attachments/assets/b19abb4f-df02-4ab9-ac02-56072cfa29e1)

### Operating System Version

Slackware64-current

### Thunderbird version

128.2.0esr (64-bit)

### Send Later version

10.5.5 (2024-09-03)

### Send Later start-up string

`Send Later version 10.5.5 on Thunderbird 128.2.0 (20240905120314) [linux x86-64] UI locale en-US, Date Locale it-IT`

**Comment by jikamens** [comment] 2024-09-13 20:31
This is a duplicate of #663. See the workaround there.

Thank you for letting me know this is still happening with TB128, I wasn't certain.

**Closed by jikamens** 2024-09-13 20:31 UTC
