### ISSUE TITLE
Send Later 8.77 TB 78.9.0 Send later not sent

### ISSUE THREAD

**Issue by JerryGlen** [Extended-Thunder/send-later#306] opened 2021-03-25 22:08 UTC
I am using Send Later 8.77
Thunderbird 78.9.0

When I send a delayed email, it
Opens the Send later dialog as expected
Allows me to choose when to send either by defined button ( I used 2 minutes) or by choosing time.
Shows up in the Drafts box
Warns me if I open it in the Draft Box that it won't be sent
If I resend or don't open it, it will be 'sent' ie, disappear from the drafts folder at the appropriate delay **BUT**

It will neither arrive at its destination or be copied to the Sent folder.

I get the same results if I use the 'Send later' icon in the upper right hand or if I use 'Send' button with the dialog box

**Comment by jph-sendlater** [comment] 2021-03-29 16:28
Have you checked in your outbox folder if the missing messages are getting stuck in there?

**Comment by JerryGlen** [comment] 2021-03-29 21:12
No it is not in the sent folder, nor is it in the drafts folder. First
place I checked.


Jerry G Gregoire


I do not live at the mercy of things I do not understand and cannot control.
I live in the Grace of Him whom I do not understand and cannot control.
Here is true peace!

**Comment by jph-sendlater** [comment] 2021-03-29 22:02
There's a folder under "Local Folders" called "Outbox". Messages pass through there on their way out the door, so there's a chance that could be the road block. Please check that directory and let me know what you find.

**Comment by JerryGlen** [comment] 2021-03-30 14:28
Yes. I didn't notice it. All delayed messages are stuck in my outbox.


Jerry G Gregoire


I do not live at the mercy of things I do not understand and cannot control.
I live in the Grace of Him whom I do not understand and cannot control.
Here is true peace!

**Comment by jph-sendlater** [comment] 2021-03-30 15:19
Ok, please follow the troubleshooting steps in the manual here: https://extended-thunder.github.io/send-later/#messages-not-being-sent-isolating-the-problem

They're a little involved, but those will really help track down what the problem is.

**Comment by jph-sendlater** [comment] 2021-04-18 15:22
@JerryGlen any word on this? Did you get it sorted out?

**Comment by jph-sendlater** [comment] 2021-04-28 15:55
Assuming this is solved. I'm closing this for now unless I hear otherwise.

**Closed by jph-sendlater** 2021-04-28 15:55 UTC
