### ISSUE TITLE
Scheduled messsages not sent, if "Drafts" is hosted on IMAP

### ISSUE THREAD

**Issue by filip-paczynski** [Extended-Thunder/send-later#512] opened 2023-01-10 18:24 UTC
Hi,
first of all - thanks for all Your work on this addon.

Recently (since around xmas, version 9.2.5, I guess) scheduled messages had stopped being sent. This only occurs if Thunderbird is set to use `Drafts` folder stored on IMAP server. The unsent messages simply stay in `Drafts`.
Upon switching to keep `Drafts` in `Local folders` - all is fine.

Some headers from 'unsent' email:
```
Content-Type: multipart/alternative;
 boundary="------------20xRLhKTpvlrCdsa4nlMt00b"
Message-ID: <7d76c4df-14b1-9751-1725-7e41037e655c@REDACTED>
Date: Tue, 10 Jan 2023 19:11:54 +0100
MIME-Version: 1.0
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101
 Thunderbird/102.6.1
From: =?UTF-8?B?8J+asiBGaWxpcCBQYWN6ecWEc2tp?= <REDACTED>
Content-Language: pl
To: =?UTF-8?Q?Filip_Paczy=c5=84ski?= <REDACTED>
Subject: test Send Later
X-Send-Later-Uuid: {b4924ba0-770d-4043-91ae-bd450adf3ddd}
X-Send-Later-At: Tue, 10 Jan 2023 19:14:00 +0100
X-Send-Later-Recur: none
Organization: REDACTED
X-Mozilla-Draft-Info: internal/draft; vcard=1; receipt=0; DSN=0; uuencode=0;
 attachmentreminder=0; deliveryformat=0
X-Identity-Key: id5
Fcc: imap://REDACTED@imap.REDACTED/Sent
```
There were no recent changes regarding IMAP server software, or sieve filters.
However, the problem may coincide with TB 102.6.1 release - I'm not sure.

If I were to guess, I'd point at this commit: https://github.com/Extended-Thunder/send-later/commit/bc40a3fa8f20d9a38ed43cc1357c2a5681507860
However, I might be entirely wrong, and I have no prior experience with TB addons or using IMAP from JS in any way.

**Comment by filip-paczynski** [comment] 2023-01-10 18:51
found this in the error console:
```
WebExtensions: LegacyColumn.getRawMessage.streamListener.OnStopRunning received 7287 bytes (exitCode: 0) [legacyColumnImplementation.js:44](jar:file:///home/REDACTED/filip.paczynski/.thunderbird/Profiles/beta/extensions/sendlater3@kamens.us.xpi!/experiments/legacyColumnImplementation.js)
```

**Comment by ratkobucic** [comment] 2023-01-27 12:05
I can confirm similar - if Drafts folder is on IMAP (which is normal those days) Send Later doesn't work - message gets sent next time I start Thunderbird (like next morning :) )
If Drafts folder is located on local computer (Local Folders), then it again not works as expecting.
Related headers when Drafts is on Local:

`X-Send-Later-Uuid: {d007e789-b842-446e-97c3-64b37e2a13a7}
X-Send-Later-At: Fri, 27 Jan 2023 12:59:00 +0100
X-Send-Later-Recur: none
X-Mozilla-Draft-Info: internal/draft; vcard=0; receipt=0; DSN=0; uuencode=0;
 attachmentreminder=0; deliveryformat=0`
 
 And errors from console:
 `WebExtensions: INFO [SL3U]: Received call to dummy CompleteGenericSendMessage 1 [sl3u.js:26](jar:file:///C:/Users/Ratko/AppData/Roaming/Thunderbird/Profiles/u541z4id.default/extensions/sendlater3@kamens.us.xpi!/experiments/sl3u.js)
 
 WebExtensions: LegacyColumn.getRawMessage.streamListener.OnStopRunning received 3245 bytes (exitCode: 0) [legacyColumnImplementation.js:44](jar:file:///C:/Users/Ratko/AppData/Roaming/Thunderbird/Profiles/u541z4id.default/extensions/sendlater3@kamens.us.xpi!/experiments/legacyColumnImplementation.js)`
 
And here is how message looks like in Drafts (4 minutes overdue for sending) 

![capture_27012023_130234](https://user-images.githubusercontent.com/6748109/215082318-e62f73c1-5e57-42a2-a5d1-0520d3f4c306.jpg)

**Comment by jikamens** [comment] 2023-07-22 19:07
Are y'all still seeing this issue?

**Comment by ratkobucic** [comment] 2023-07-24 07:16
I had to revert to 9.1.1 version, and disable auto-update - so that one works for me. 
Newer versions - not working, and I was too busy to play with extension every new version (update, then downgrade again)

**Comment by filip-paczynski** [comment] 2023-07-24 09:54
Yup, issue is still present on Thunderbird 102.13.0 with SendLater 9.2.9

**Comment by jikamens** [comment] 2023-07-26 21:25
Do y'all have more than 100 messages in the Drafts folder that has this problem? If so, then I suspect the root cause of your issue is #529, which will be fixed in the next Send Later release.

**Comment by ratkobucic** [comment] 2023-07-27 05:58
No, my Drafts have no more than 20 messages...

**Comment by filip-paczynski** [comment] 2023-07-27 09:15
I had 294 messages in Drafts.
1. Moved them all to a subfolder
1. Compacted Drafts folder
1. Repaired Drafts folder
1. Restarted Thunderbird
1. Drafts are now totally empty and take up 0 bytes of disk space
1. Tested Send Later - did not work :(

I'll try to go through [this procedure](https://github.com/Extended-Thunder/send-later/issues/549#issuecomment-1646636451) during the weekend

**Comment by filip-paczynski** [comment] 2023-07-27 10:19
Since mine issue is resolved, and as it seems, it was not related to IMAP, but rather to folder size (#529), I'm closing this issue.

@jikamens Thanks for help

**Comment by jikamens** [comment] 2023-08-08 20:20
I'm reopening this issue because there are several other people who've commented here that it's not resolved for them.

If those of you still experiencing this issue are able to try out the [TB115 beta release](https://github.com/Extended-Thunder/send-later/releases/tag/v10.0.0) and see if it's fixed there, that would be great. Otherwise eventually the fixes in that release will be backported to a Send Later release that's compatible with TB102. I'll comment here when that happens.

**Comment by mbfdias** [comment] 2023-08-09 13:31
switching to keep Drafts in Local folders - fixed the problem for me and send later hadn't been working since months...  updated to TB115 + v10.0.0 and switched all accounts to keep drafts in local folders - Drafts :) and it started working again.

**Comment by jikamens** [comment] 2023-08-09 13:41
I an closing this issue because I believe it's resolved. Please reopen or comment if you're still seeing Send Later working for Drafts on Local Folders but not working for Drafts on IMAP.

**Closed by jikamens** 2023-08-09 13:41 UTC
