### ISSUE TITLE
E-mails empty after first one sent in Thunderbird 94.0 (beta)

### ISSUE THREAD

**Issue by dib0** [Extended-Thunder/send-later#385] opened 2021-10-10 12:06 UTC
Hi,

I'm on Thunderbird 94 (beta). After sending an e-mail (not using send it later, just sending it) any following e-mail will be sent empty (empty subject and content). The first one goes through alright, none after that. Restarting Thunderbird will allow me to send another e-mail (none after that as well).

After some testing and trying I found out that this behavior goes away when disabling the Send It Later extension. Can't find anything in the error console logs.

**Comment by jph-sendlater** [comment] 2021-10-10 20:18
Thanks for checking all that. Just a couple more questions for right now:
* There are three ways to initiate a send in Thunderbird (`File>Send` , `Ctrl+Enter`, and with the "Send" button in the tool bar). Does this happen with all three methods, or just some of them?
* Could you post a screenshot of your Send Later preferences? In particular, I'm interested in whether you're using anything that affects the initial send operation, like "Send does Send Later", or "Send delays messages by ...".


Thank you for reporting this. I'll look into it as soon as I get a chance.

**Comment by jph-sendlater** [comment] 2021-10-10 20:20
Oh, and one last thing that I should have asked before: does this happen with messages that you sent using Send Later, or just with messages that you send directly, without scheduling them?

**Comment by dib0** [comment] 2021-10-11 16:44
Strange... not being able to replicate will complicate fixing it indeed...

I don't have many extensions. Here's my list:
![image](https://user-images.githubusercontent.com/3939328/136825783-847f721e-8e8b-4f2e-af75-f5ee57b27e96.png)

I did a test by disabling all extensions and enabling Send Later, but the problem persists... If I can check anything / enable some logging etc, please let me know.

**Comment by jph-sendlater** [comment] 2021-10-24 00:31
Sorry for delays getting to the current open issues. I just started a new job, which is eating up a lot of time and mental bandwidth. Development on send later are low priority for me right now, and will be until I get settled into the new job.

If you want to contribute code to fix this (or know anyone who would be willing to help) it would be very much appreciated. I'd happily pass along future donations to anyone who's willing to contribute.

I'm duplicating this message to all the open issues. Sorry again for the delays!

**Comment by jph-sendlater** [comment] 2022-11-13 22:30
Closing this because it hasn't been touched in a long time, but please open a new ticket if the problem is still occurring.

**Closed by jph-sendlater** 2022-11-13 22:30 UTC
