### ISSUE TITLE
Mac: Command+Shift+Enter no longer sends later

### ISSUE THREAD

**Issue by JimFuoco** [Extended-Thunder/send-later#150] opened 2020-11-24 02:00 UTC
In older versions,  Command+Shift+Enter would trigger the "Send at [DATE][TIME]" function. But in v8.2.1 on Thunderbird 78.5.0, it doesn't. And Command+Enter sends immediately.

**Comment by jperryhouts** [comment] 2020-11-24 02:05
Are you referring to cmd+shift+enter from the main composition window opening the send later dialog, or cmd+shift+enter executing "send at..." when the popup is already open? I initially interpreted this as the former when you mentioned this in #101, but this title sounds more like the other interpretation, which is the same as #27

**Comment by jperryhouts** [comment] 2020-11-25 02:44
I'm assuming this is indeed a duplicate of #27 - Let me know if not and I can open the issue back up.

**Closed by jperryhouts** 2020-11-25 02:44 UTC
