### ISSUE TITLE
Date in SendLater column in Drafts folder does not conform to locale settings

### ISSUE THREAD

**Issue by tplanter** [Extended-Thunder/send-later#196] opened 2020-12-02 01:37 UTC
I'm in Australia where  the locale settings' dates are written 1/12/2020 (1st December 2020), not 12/1/2020. 12/1/2020 is what is displaying.
![SendLater date 2020-12-02 123415](https://user-images.githubusercontent.com/73688736/100816815-16addb80-349b-11eb-8ce8-fb1eb0805eb3.png)

**Comment by jperryhouts** [comment] 2020-12-02 02:03
Duplicate of #154

**Comment by tplanter** [comment] 2020-12-04 01:18
This is NOT fixed in version 8.5.3
![SendLater 2020-12-03 140454](https://user-images.githubusercontent.com/73688736/101109332-c5cced00-362a-11eb-8e96-c80d064ecffd.png)

**Comment by jperryhouts** [comment] 2020-12-04 01:56
Just to be certain, try restarting Thunderbird and verifying that your send later version is actually registering that it is on version 8.5.3. It might not actually complete the upgrade without a restart, which isn't very transparent from the UI.

After that, try copying each of the following into your debug console (crtl+shift+J), then hitting enter after each one and recording the output. Let me know what the output is.

```
navigator.languages
```

```
Sugar.Date.getLocale().code
```

```
new Intl.DateTimeFormat([], { hour: "numeric", minute: "numeric", month: "numeric", day: "numeric", year: "numeric" }).format(new Date())
```

**Comment by tplanter** [comment] 2020-12-04 03:15
T'bird and the machine have both been re-started (T'bird a few times) since the update - still showing as v8.5.3

Output from Error console is:
14:06:56.726 navigator.languages
14:06:56.746 Array [ "en-US", "en" ]

14:08:22.823 Sugar.Date.getLocale().code
14:08:22.843 "en"

14:08:59.574 new Intl.DateTimeFormat([], { hour: "numeric", minute: "numeric", month: "numeric", day: "numeric", year: "numeric" }).format(new Date())
14:08:59.594 "12/4/2020, 2:08 PM"

**Comment by jperryhouts** [comment] 2020-12-04 04:34
That's really weird. It looks like the Date column respects the system settings, but everything else is given Thunderbird's locale settings. Try checking your preferences under "General" > "Language". I'm guessing that is set to "English (United States)". If so, then use the "Set Alternative" button and add the right locale. Let me know if that's not the case.

**Comment by tplanter** [comment] 2020-12-04 06:33
The screenshot is before changing Language.
![Tbird language 2020-12-04 154239](https://user-images.githubusercontent.com/73688736/101129935-a64bb980-3656-11eb-9845-b94d38d00ef3.png)
I've now changed language to the only other English option available - United Kingdom.
This fixes the issue. Can't say I've had to change to UK before to fix a date problem.

**Comment by jperryhouts** [comment] 2020-12-04 17:22
Yeah, weird situation but add-ons don't have access to operating-system-level settings, and that option is what gets passed along from Thunderbird :shrug: Glad it's fixed in any case.

**Closed by jperryhouts** 2020-12-04 17:22 UTC
Labels: duplicate
