### ISSUE TITLE
Please consider supporting TB version 115

### ISSUE THREAD

**Issue by tzenker-tzc-itexperts** [Extended-Thunder/send-later#561] opened 2023-07-15 12:12 UTC
Dear send later team,
compatibility check for Thunderbird (screen shot below) marked that
Send Later is not compatible with upcoming TB 115.
Please consider supporting TB version 115.

![TB_115_send_later](https://github.com/Extended-Thunder/send-later/assets/117731736/32910408-5295-4676-8350-f76b41bc98b6)

**Comment by arndissler** [comment] 2023-07-15 21:10
I mark this as a duplicate of #551 (see and track comments over there).

**Closed by arndissler** 2023-07-15 21:10 UTC
Labels: duplicate
