### ISSUE TITLE
"Send Later" hot-keys and "Send does Send Later" option are not working

### ISSUE THREAD

**Issue by JimCarls** [Extended-Thunder/send-later#130] opened 2020-11-20 20:56 UTC
With the newest version, only the Send Later button on the composition window works. I've tried Ctrl-Shift-Enter, Ctrl-Alt-Enter and "Send does Send Later" and none of these settings have any effect. Oddly, in the pre-official-release the "Send does Send Later" did work (I had not tried the other options, though).

**Comment by jperryhouts** [comment] 2020-11-20 21:11
Can you confirm what version of Send Later you're on, and in which version these functions were last working for you?

Seems like silly advice, but this sounds like the kind of thing that might be fixed by restarting Thunderbird if you haven't done that since the last Send Later update. That shouldn't be necessary, but when updating addons there's always a chance of Thunderbird not cleaning up properly from the previous version, which can cause unexpected behavior especially in user interface things like this.

**Comment by JimCarls** [comment] 2020-11-20 21:50
It's 8.1.3.  Well, that's weird. I shut it down again and it all works 
now. However I was really sure that I did that after installing the 
update (because I had the pre-release version). Perhaps deleting the 
pre-release version, installing the update and then restarting was 
jamming too many changes together.

Never mind!

**Comment by jperryhouts** [comment] 2020-11-20 21:55
Huh, well that's good to hear anyway.

Thunderbird add-ons are in a state where they are all installed as "restartless", even though all the things that required restarts in previous versions still exist. Unfortunately there are a lot of places for Thunderbird to get its wires crossed during those upgrades :shrug:

**Closed by jperryhouts** 2020-11-20 21:55 UTC
