### ISSUE TITLE
Messages delayed by Send Later disappearing

### ISSUE THREAD

**Issue by tplanter** [Extended-Thunder/send-later#235] opened 2020-12-10 00:20 UTC
I've just had the issue (again) where I was replying to an email (gmail IMAP account, SendLater v8.5.3, TB v78.5.1), pressed the SendLater 5 minute delay and the message disappeared. Didn't appear in Drafts, but the message was marked as replied to in the Inbox.

I thought it might be an issue with my Drafts folder as there were a number of drafts left in there after messages had been successfully sent, so I discarded them in Gmail web browser, checked they were deleted in TB, repaired the folder.
Then replied to the message again and clicked the 5 minute delay in SendLater. Same issue - message disappeared.

Replied to the message again and clicked the 15 minute delay in SendLater. Same issue - message disappeared.

Replied to the message again and clicked send now. Message sent successfully..

**Comment by tplanter** [comment] 2020-12-10 01:00
An update:
I've just closed TB and restarted it, then repaired the Drafts folder (there was nothing in it) and replied to a message, selected SendLater 5 minute delay.
5 minutes are up and the message now appears in the Send folder, as well as the version in the Drafts folder having a line through it showing it has been deleted.  I think the disappearance of the message from the Drafts folder is dependent upon the Gmail deletion settings. Is this correct?
This really doesn't throw any light on the disappearing message issue, though - other than the standard computer problem cure of rebooting often works!

**Comment by corwinou** [comment] 2020-12-14 14:58
I also have similar troubles with a message that should have been sent later... but never did. It was a new message, not a reply. While checking sent and draft folders, no clue where it has fallen...  (TB 78.5.1 x64 / SL 8.5.4)
Any advice ?

**Comment by jph-sendlater** [comment] 2020-12-14 16:40
Sorry, I had accidentally turned off notifications and didn't see this issue until now!

There is a new release of Send Later (8.6.5) waiting on Thunderbird review. I would expect it to be available later today, depending on the reviewers' schedules. Please give that version a try as soon as it's available (be sure to restart Thunderbird when you upgrade), and let me know if the problem persists. I just want to be sure we don't spend time tracking down a bug that has already been fixed or changed.

**Comment by vaccoda2020** [comment] 2020-12-15 11:30
Hi guys,

I have 8.6.5 installed and having the same issue. Wrote an email to send 15 mins later, then it disappeared - checked Drafts and not in there either.

Cheers,

Rob

**Comment by vaccoda2020** [comment] 2020-12-15 17:25
Update to previous comment:

The issue has occurred again. I restarted TB, and then I was presented with the error as per screenshot in previous message, and then if I click "retry" it'll save the message to drafts to send. If I then do another email via send later, it will save correctly to drafts and the error doesn't show. It seems to be a sporadic error. 

I have just also this minute updated TB to 78.6.0 - might resolve the issue?

Thanks,

Rob

**Comment by jph-sendlater** [comment] 2020-12-15 18:04
I'm not positive that you're all having the same problem. It sounds like each person who's posted here has described a distinctly different issue.

Question for everyone who's still experiencing similar issues: Do the affected messages show up in your Outbox at any point during this process?

**Comment by jph-sendlater** [comment] 2020-12-15 18:09
@vaccoda2020 Your particular issue appears to be with your email server or internet connection. If the "retry" or "save" button does eventually put the message in Drafts, then this seems fine, and nothing send later can really do about it.

**Comment by jph-sendlater** [comment] 2020-12-15 18:26
@tplanter 

> 5 minutes are up and the message now appears in the Send folder,

If the message shows up in the "Sent" folder, then it has been sent.

> as well as the version in the Drafts folder having a line through it showing it has been deleted.

It sounds like you're using the Thunderbird "Mark message as deleted" option rather than "Move to Trash folder" - Is that right?

> I think the disappearance of the message from the Drafts folder is dependent upon the Gmail deletion settings. Is this correct?

Gmail IMAP does seem to be tricky in general, since they use things like "virtual folders", and flags to track messages, rather than traditional folder structures. That's how messages can show up in "All Mail" and also "Sent", and in the conversation view of related messages from other folders when you're using the web interface. Send Later should be compatible with all that, but it's certainly a prime suspect if messages are behaving inconsistently.

> This really doesn't throw any light on the disappearing message issue, though - other than the standard computer problem cure of rebooting often works!

A surprising number of things in Thunderbird seem to be fixed by restarting. Seemingly more so than most other software. :shrug:

If I understand correctly, it sounds like things are tentatively working for you? Let me know if I misunderstood, or if that changes.

**Comment by corwinou** [comment] 2020-12-15 21:08
I now use v8.6.5 and the small tests I made were ok, but in the previous months it worked fine also before this strange issue. Not sure what to think about it ! 
TB is kept open for many days or weeks while the PC is put in standby once a day.

**Comment by weboutreach** [comment] 2020-12-15 23:45
Win10 + TB 32bit + Standard Dovecot / Postfix server:
SL8.0.5 TB78.5.1 Messages appear to be scheduled, and go into Drafts folder, but eventually just disappear completely, not in Drafts folder, not in Deleted.
SL8.6.5 TB78.6.0 Messages appear to be scheduled, and go into Drafts folder, but are never sent, they just stay in the Drafts folder. Restarting TB doesn't try and send messages that should have been sent. Clicking on the 
![Capture](https://user-images.githubusercontent.com/5333458/102286135-91610700-3f2f-11eb-9fb5-922d7fae8584.JPG)

**Comment by jph-sendlater** [comment] 2020-12-16 00:07
@weboutreach Are the missing messages in the Outbox?

**Comment by tplanter** [comment] 2020-12-16 04:20
I think this is a Gmail IMAP/Thunderbird issue, which, if used in conjunction with SendLater, causes problems. 
I have one POP3 non-Gmail account, and don't seem to get any issues with that POP account.
I have done a number of tests, first closing and restarting Thunderbird, then sending 2 messages (1 from my various Gmail IMAP/Thunderbird accounts. Most worked, one didn't and both the messages disappeared, and now Thunderbird is telling me I have a corrupt Drafts folder, but this isn't the account where the message disappeared.
I have sent a further email using SendLater delay of 15 mins from the account with a corrupt folder, and SendLater has dealt with the message correctly,, it's been transferred to the Sent folder and I've received it OK. SendLater now shows PEND 1 message 
No missing messages go to the Outbox.
I've checked all the Thunderbird settings > copies & Folders > Drafts and Templates settings and they are the same across all 4 Gmail accounts. They all say Keep draft messages in Other > Drafts on xxxxx@gmail.com.
I've looked at the Gmail Settings in the browser and they all appear to be the same.
I'm currently on SendLater v8.5.4.
I'm currently on TB v78.5.1, and I've just been offered the update to TB v78.6.0. Will update and test again when I've fixed the corrupt Drafts folder issue - again!

**Comment by weboutreach** [comment] 2020-12-16 10:22
@jph-sendlater No, they're not in my Outbox. Actually I've just discovered that I don't have an Outbox. A rummage around the settings of Thunderbird lead me to the local folder settings where I found out that I put the local folder on the network, and I'm not connected to that at the moment. Doh! I just changed the local folder to a genuinely local folder and restarted Thunderbird. My Outbox has come back and Send Later now works. Please ignore my previous message, I am an idiot, and thanks for the prompt to look for the Outbox. Hope that helps someone.
![local-folder-message-storage-local-directory](https://user-images.githubusercontent.com/5333458/102335616-0e1fcf80-3f88-11eb-9a71-12121eb6c14b.jpg)

**Comment by jph-sendlater** [comment] 2020-12-16 16:57
@weboutreach Thanks for following up. That possibility hadn't even occurred to me- I'm sure it will be helpful to someone in the future. I'll put a mention about it in the manual when I have a chance.

**Comment by reinhard512** [comment] 2020-12-22 09:21
Yesterday I noticed the same problem - messages scheduled with Send Later are just disappearing. Concers replies as well as new messages. Using Thunderbird 78.6.0 with Send Later 8.6.5 and different IMAP mailboxes hosted at Strato.de. Today I had the same problem with another eMail-address at Strato.de.

In my case the following workaround helped:

1. Close Thunderbird
2. Restart Thunderbird
3. Compress the Folder Draft of the respective Mailbox
   (Komprimieren des Ordners Entwürfe des betroffenen Postfaches)

Then everything was working as expected.

I am not sure if this is a bug in Send Later. Could be a bug  at Strato.de.

Best regards
Reinhard

**Comment by jph-sendlater** [comment] 2020-12-22 17:50
I still don't know what would be causing this, but I'm thinking that something about the way Send Later does the Save draft -> Close window transition is the problem. i.e. if Send Later thinks the draft save operation is complete, and closes the compose window, but Thunderbird has not yet finished saving. I don't really see how that would have been possible, but #256 asks Thunderbird to automatically close the compose window when it finishes saving, rather than handling both operations manually. I'm hoping that helps. I'll bundle it up into a beta release package later today.

**Comment by jph-sendlater** [comment] 2020-12-22 23:01
If anyone wants to give version 8.7 a try, it is available via the [github release page](https://github.com/Extended-Thunder/send-later/releases/tag/8.7.0).

Main change that I think might solve this issue is that Send Later takes an even more hands off approach to saving draft messages. It no longer manually closes the composition window, and lets Thunderbird handle those details instead.

**Comment by reinhard512** [comment] 2020-12-28 11:53
Tried version 8.7.0 and problem did not come up again.

**Comment by jph-sendlater** [comment] 2020-12-28 16:50
Great to hear! I'm fairly confident at this point that the problem is indeed fixed in 8.7.0, but I'll wait for it to go live on ATN before I close this issue. I actually submitted it for review about a week ago, but I assume the Thunderbird reviewers are on holiday so it might not be approved until after new years.

**Comment by jph-sendlater** [comment] 2021-01-01 21:45
I'm going to optimistically (naively?) close this issue, assuming it is indeed fixed in 8.7.1. Do let me know if you find that isn't the case and I'll open it back up.

**Closed by jph-sendlater** 2021-01-01 21:45 UTC
