### ISSUE TITLE
Send later no longer works

### ISSUE THREAD

**Issue by adjustGirl** [Extended-Thunder/send-later#546] opened 2023-06-28 09:41 UTC
With my e-mail client, sending no longer works at all. It also has nothing to do with whether my iMac is asleep or not. Many attempts have been unsuccessful.

Thunderbird 102.12.0 and Sendlater 9.2.9

**Comment by jikamens** [comment] 2023-07-18 17:01
Hi! Sorry for the delay getting back to you about this.

If it's still an issue, then can you be more specific about what you mean when you say "sending no longer works at all"? Do you mean you can't schedule a message, or after you schedule a message it doesn't show up as being scheduled, or it shows up as being scheduled but doesn't send at the scheduled time, or something else?

Thanks.

**Comment by adjustGirl** [comment] 2023-07-18 17:09
I can do everything as intended, but the message will not be sent at the scheduled time.
I've tried a few more times now. Still

**Comment by jikamens** [comment] 2023-07-18 17:15
Please follow [the instructions in the user guide](https://extended-thunder.github.io/send-later/#debug-logging) for capturing a debug log.

At step 5 of those instructions, schedule a message to be sent one minute into the future, then wait three minutes after scheduling it, then finish the rest of the log capture instructions.

You can email the logs to me at jik@extended-thunder.org rather than posting them here.

Thanks!

**Comment by adjustGirl** [comment] 2023-07-21 11:14
Nothing remarkable. The plug-in queries the accounts at regular intervals, nothing more.

**Comment by jikamens** [comment] 2023-07-21 12:52
I need to see the log.

**Comment by adjustGirl** [comment] 2023-07-23 09:34
Sorry, but unfortunately I'm in the hospital, and can't take care of it. Maybe someone else?

**Comment by jikamens** [comment] 2023-07-23 13:17
Sorry to hear that! Hope you're better soon. We can circle back later if necessary, but there is a bunch of work being done to make the add-on more robust which I hope will come to fruition soon, so it's possible that will address your issue even though we haven't identified a specific root cause here.

**Comment by jikamens** [comment] 2023-07-26 21:12
If you have more than 100 messages in your Drafts folder, then this is probably #529. Please confirm whether that's the case. If so, we should revisit once we release the fix for that issue to see if things are working for you again.

**Comment by jikamens** [comment] 2023-08-09 13:37
Going to close this issue because I believe it's resolved. If you're still seeing it in TB109 with Send Later 9.3.0 or any newer 9.x release, or in TB115 with Send Later 10.0.1 or any newer 10.x release, feel free to reopen this issue. Or comment if GitHub won't let you reopen.

**Closed by jikamens** 2023-08-09 13:37 UTC
