### ISSUE TITLE
Presence of PGP key leads to draft error on unencrypted messages

### ISSUE THREAD

**Issue by mpldr** [Extended-Thunder/send-later#492] opened 2022-12-05 18:46 UTC
Hi,
similar to #200, but the Draft – as well as the message sent itself – are unencrypted. It seems the mere presence of a PGP key throws off the plugin. This would only be minor if the message was actually sent at the specified time, but it isn't. Sending it using the "Send now"-Button works on the scheduling dropdown works just fine though. (the sent mail is not signed or encrypted either)

**Comment by jikamens** [comment] 2023-07-22 18:44
I can't reproduce this issue. Are you still seeing it?

**Comment by mpldr** [comment] 2023-07-27 12:22
We have not used send later since.

**Comment by jikamens** [comment] 2023-08-08 20:17
I'm going to close this issue as not reproducible. If you do manage to reproduce it with the current release (or the [TB115 beta release](https://github.com/Extended-Thunder/send-later/releases/tag/v10.0.0) please comment here with details and I will reopen the issue.

**Closed by jikamens** 2023-08-08 20:17 UTC
