### ISSUE TITLE
Pop-up dialog receiving inconsistent styles with system dark theme

### ISSUE THREAD

**Issue by mcodygit** [Extended-Thunder/send-later#201] opened 2020-12-03 15:17 UTC
Hi,

Send Later pop-up format.
Cannot see texts black on black.
Also font size is very small.

I tried a number of different TB themes in case this was the issue, but always the same.

Is this something I can customize? If so where?

Thank you,
Michael

![image](https://user-images.githubusercontent.com/75435645/101048192-58618380-357a-11eb-8a41-f198941a59fb.png)

**Comment by jperryhouts** [comment] 2020-12-03 16:07
What operating system are you on? Do you have a black system theme?

**Comment by mcodygit** [comment] 2020-12-03 17:54
Hi,
I should have mentioned OS.
Windows 10. I have tried some different themes and color settings (restarted TB each time), no difference.
I should also say this was working fine until I did upgrade to TB78 (and update of SendLater).

Is there a configuration file somewhere I can edit?

Thanks,
Michael

**Comment by jperryhouts** [comment] 2020-12-03 18:00
Are you referring to Thunderbird themes? I don't know if Windows has system-wide themes, but those would be separate from the Thunderbird theme if so.

Does this happen to any other components in Thunderbird, or only the send later popup?

**Comment by jperryhouts** [comment] 2020-12-05 21:15
This might be fixed in [version 8.6.1](https://github.com/Extended-Thunder/send-later/releases) but I don't know for sure because I don't really know what's causing it to begin with.

**Comment by jperryhouts** [comment] 2020-12-07 18:08
I was finally able to reproduce this with an older Thunderbird version, which would not respect any CSS styles at all. All HTML elements in popup dialogs were partially styled by the system theme with no way to override those styles.

That seems to be fixed in Thunderbird version 78.5.1.

**Comment by mcodygit** [comment] 2020-12-07 21:28
Hi,

Tried v8.6.1 and seem to have TB v78.5.1.

But still have issue.

Anywhere I can edit config/css to try change?

Thanks,
Michael
![image](https://user-images.githubusercontent.com/75435645/101407567-fd5dc280-38d2-11eb-89d5-7a3a15b52bc6.png)

**Comment by jperryhouts** [comment] 2020-12-07 22:34
You can install the development version by downloading the source code [here](https://github.com/Extended-Thunder/send-later/archive/master.zip). Unzip that file somewhere, then in Thunderbird's extension manager click the gear icon > "Debug add-ons" > "Load temporary add-on..." and open the file "manifest.json" from whereever you unzipped the source code.

The relevant file is called "popup.html" in the "ui" directory. Editing that file should take effect immediately, without re-loading anything.

Let me know what you find.

**Comment by jph-sendlater** [comment] 2020-12-09 18:12
I found a mozilla bug report about this: https://bugzilla.mozilla.org/show_bug.cgi?id=1399259 but it mentioned nothing about these elements being unresponsive to CSS styling, and the Firefox devs marked it as "wontfix" for some reason.

I opened a new bug about it with Thunderbird: https://bugzilla.mozilla.org/show_bug.cgi?id=1681561
We'll see if that gains any traction.

**Comment by jph-sendlater** [comment] 2021-04-28 16:12
This appears to be fixed in the latest beta version of Thunderbird

**Closed by jph-sendlater** 2021-04-28 16:12 UTC
