### ISSUE TITLE
TB very slow with version 9.2.4

### ISSUE THREAD

**Issue by AlainRnet** [Extended-Thunder/send-later#497] opened 2022-12-14 00:05 UTC
Since 2 days, TB under Manjaro Linux is very slow (15-20 seconds to display an email, lag during email redaction, etc.) I disabled all modules to find that send-later was the problem. Installing the previous version solves the problem.

TB 102.5.0 (64 bits)
Mozilla Thunderbird for Arch Linux

**Comment by igustin** [comment] 2022-12-15 07:38
Same here, and scheduled mail never leaves Draft folder.

**Comment by ehws** [comment] 2022-12-15 22:00
Same here with TB 102.5 (x64)

When I disable V9.2.4, TB is back to normal...

**Comment by alfazaz** [comment] 2022-12-20 16:57
Same here. And duplicate of #495 I think...

**Comment by esdaniel** [comment] 2022-12-21 16:13
Confirmed 'here' too, significantly impacts the responsiveness of the UI making Tbird unusable when the extension is enabled.

**Comment by jph-sendlater** [comment] 2022-12-24 01:17
Using more built-in, general-purpose API's has meant losing a lot of optimization. Version 9.2.5 tries to mitigate that by reducing the overall number of API calls. That's been submitted to ATN and awaiting approval. Please let me know if it solves the performance issues.

**Comment by jikamens** [comment] 2023-07-22 18:48
@AlainRnet @igustin @ehws @alfazaz @esdaniel are any of you still seeing this issue?

**Comment by alfazaz** [comment] 2023-07-22 20:07
@jikamens I don't know because I stopped using this extension.

**Comment by igustin** [comment] 2023-07-24 07:45
> @AlainRnet @igustin @ehws @alfazaz @esdaniel are any of you still seeing this issue?

I reverted to 9.1.1 which still works fine and didn't upgraded since then.

**Comment by AlainRnet** [comment] 2023-07-26 15:51
Actually 9.2.9, everything's all right.

**Comment by AlainRnet** [comment] 2023-07-26 15:51
Sorry, it's on Elementary OS, I have to check the version on Manjaro.

**Comment by jikamens** [comment] 2023-08-09 13:46
If you are still seeing significant performance issues please make sure your Drafts folder(s) have local synchronization enabled. Otherwise Send Later needs to download from the IMAP server every message in your Drafts folder every time it scans.

Closing this issue because I believe it is resolved. If you're still seeing it in Send Later 9.3.0 or 10.0.1 with local Drafts synchronization enabled, please reopen or comment on the issue.

**Closed by jikamens** 2023-08-09 13:46 UTC
