### ISSUE TITLE
Editing scheduled message doesn't cancel schedule at start of edit

### ISSUE THREAD

**Issue by jikamens** [Extended-Thunder/send-later#62] opened 2020-10-31 20:05 UTC
In TB68 when you start editing a scheduled message it cancels the scheduled send time in the message right when you start editing it, and pops up a message telling you it has done so, with a checkbox allowing you to suppress that warning in the future.

The TB78 version of Send Later does not do this.

This is a significant and perhaps a blocker. The reason this functionality exists is to prevent a scheduled message from being sent out from under someone when they're in the process of editing it.

At the very least, the add-on needs to pop up a warning telling the user that if they want to cancel the scheduled send, they need to save the draft themselves.

**Comment by jperryhouts** [comment] 2020-10-31 22:18
Non-ideal workaround that's implemented right now is that Thunderbird checks any open messagecompose windows for the `message-id` header before sending anything. This is very opaque to the user, so is just a temporary workaround, but it does work and will prevent accidentally sending an active draft.

Idiosyncrasies about this approach:
* If the user saves the edited draft (through the usual ctrl-s or file>save) its schedule will be removed, consistent with previous versions.
* If they re-schedule via the SL dialog then a new draft (with the new schedule) is created and the old one removed.

All of that is approximately the same as the TB68 version approach. The problem is really that there is no obvious indication to the user that this is the case. I do like certain aspects of this method though, because you can open a draft in a compose window without dropping its schedule. If you close it without making any changes then it remains scheduled.

I'll think more about whether this is a blocking bug after I finish working on #59. I think I have a reasonably good solution to that, which I'll try to roll out as another beta release later this afternoon and I'll get to this one tomorrow.

**Comment by jikamens** [comment] 2020-10-31 23:57
Didn't realize you already had something in place to deal with this, just using a different approach. Definitely not a blocker then. Perhaps not even a bug at all. :shrug:

**Comment by ribz** [comment] 2020-11-03 08:03
I'm not sure this workaround would work with the server side use case ([https://blog.kamens.us/send-later/#server-side](https://blog.kamens.us/send-later/#server-side)) or in the case where you compose a message on one instance of Thunderbird and then edit the draft on another,

**Comment by jikamens** [comment] 2020-11-03 14:20
@ribz that's a great point. @jperryhouts take note!

**Comment by jperryhouts** [comment] 2020-11-03 16:18
Yes, that's a good point. I do plan to go back to the old functionality soon. If you need this functionality in the mean time just hit ctrl-s when you open a draft and the headers should disappear.

**Closed** 2020-11-29 01:16 UTC
